### PR TITLE
Custom updater modal

### PR DESCRIPTION
**Pull request by pierremtb**
Todo:
- [x] Update branch to main (stuck in the past on purpose so we always get dialogs for dev)
- [x] Figure out how we can actually test this (added component tests for now)

@franknoirot I'll let you provide guidance on UI and UX. That's the current state of things

image

image

Tested on Windows too (no relaunch modal as it opens the msi directly)
image

### CODE REVIEW

**Comment by franknoirot** [comment]
Oh sick @pierremtb! I was just about to ask how it handles a long change log before you updated the image, perfect.

Could we get the markdown to render as HTML?

My only thoughts while mocking up [this](https://www.figma.com/file/5UUPOawPLEs3D0Gptf42vy/Designs?type=design&node-id=1947-17216&mode=design&t=gT8NQtTJgeSbCPub-11) were:
1. Show a Zoo logomark in the overlay so that it feels more like an official notice
2. Reuse the [styling we have on the "Alpha" pill from the onboarding](https://github.com/KittyCAD/modeling-app/blob/main/src/routes/Onboarding/Introduction.tsx#L137-L139) to highlight the version number
3. Render the markdown to HTML to get better list styling especially

Updater Dialog

(Ignore the button styling and the fact that this modal has opened over the `/file` page view. The buttons are the next look-and-feel and I haven't gotten a good mockup of the home view yet)

**Comment by pierremtb** [comment]
Awesome thank you @franknoirot! I'll update it to match the mockup.

Yeah we can used `Marked.parse` from https://github.com/ts-stack/markdown that we already depend on and inject the result. Just have to figure out how to do it safely

**Comment by pierremtb** [comment]
image
 
With v0.16.0. We're still missing the bullet points (due to inheritance and I really know how to fix it yet). Will update to main

**Review by jgomez720 — APPROVED** [review]
I don't think I have a way to test it, but everything looks good to me. I like it!

**Comment by pierremtb** [comment]
Alright tests are green. Did as much manual testing as I could. @franknoirot Let me know if the design meets your expectations (I know we're lacking bullet points for now)

**Comment by pierremtb** [comment]
Moved to draft until we merge #1400 (already rebased on it)

**Comment by franknoirot** [comment]
Yeah no worries on the bullet points, I might be able to take a look at the CSS and fix in a follow-up PR if you should me how to test it in dev @pierremtb.

**Comment by pierremtb** [comment]
@franknoirot Sounds good! Let's wait for the next update, this branch is easier to test when it's a version behind :)

**Comment by pierremtb** [comment]
@franknoirot Waiting on another nightly build to verify that the regular update flow still works as expected. After that I think we should trigger a release, and then get on with this one

**Comment by pierremtb** [comment]
Okkkkk @franknoirot we need this merged sooner than later actually 😅 I don't know how I missed this during the migration to tauri v2 #1400 
> The built-in dialog with an automatic update check was removed, use the Rust and JS APIs to check for and install updates instead.
from https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#migrate-to-updater-plugin

We can fake a nightly build locally and point to https://storage.googleapis.com/dl.kittycad.io/releases/modeling-app/nightly/last_update.json with the following
```
VERSION=24.4.16 yarn bump-jsons
echo "$(jq --arg url 'https://dl.zoo.dev/releases/modeling-app/nightly/last_update.json' \
            '.plugins.updater.endpoints[]=$url' src-tauri/tauri.release.conf.json --indent 2)" > src-tauri/tauri.release.conf.json
echo "$(jq --arg id 'dev.zoo.modeling-app-nightly' \
            '.identifier=$id' src-tauri/tauri.release.conf.json --indent 2)" > src-tauri/tauri.release.conf.json
echo "$(jq --arg name 'Zoo Modeling App (Nightly)' \
            '.productName=$name' src-tauri/tauri.release.conf.json --indent 2)" > src-tauri/tauri.release.conf.json
yarn tauri build -b -c ./src-tauri/tauri.release.conf.json
./src-tauri/target/release/Zoo\ Modeling\ App\ \(Nightly\)
```
image

**Review by franknoirot — APPROVED** [review]

**Pull request merged**
