### PR TITLE
Cut release v0.25.0

### PR DESCRIPTION
**Pull request by pierremtb**
closes https://github.com/KittyCAD/modeling-app/issues/3757

## What's Changed
* We migrated desktop app platforms! and we wrote 50+ new tests to celebrate 😄 
* Lofts are now available in KCL code (#3681)
* KCL now allows multi-line comments in `|>` expressions (#3731)
* KCL breaking change: replace `tanArc(to)` with `tanArcToRelative` (#3729)
* Execution now halts when swapping files (#3703)
* Newly redesigned sign-in page (#3684)
* Too many bug fixes, tests, and deep system improvements to count
* And official welcome to the frontend team for Kevin, Lee, and Jon ❤️

**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.24.12...v0.25.0

### CODE REVIEW

**Comment by jessfraz** [comment]
just wanna make sure we wait on the 4 things pending here :) https://github.com/orgs/KittyCAD/projects/32/views/1

**Comment by pierremtb** [comment]
Got three actions to look at for updater tests:
- https://github.com/KittyCAD/modeling-app/actions/runs/10692379931 a 0.25.0 electron build pushed to a test side of the bucket
- https://github.com/KittyCAD/modeling-app/actions/runs/10692413196 an update that should pop up on that 0.25.1 build
- https://github.com/KittyCAD/modeling-app/actions/runs/10692410056 a tauri build of the latest branch pointing to that test side of the bucket

Should test the whole tauri-to-electron-to-electron flow

**Comment by pierremtb** [comment]
Nevermind, two new test builds to look for:
- https://github.com/KittyCAD/modeling-app/actions/runs/10693616319
- https://github.com/KittyCAD/modeling-app/actions/runs/10693626212

**Comment by pierremtb** [comment]
Confirmed with:
- https://github.com/KittyCAD/modeling-app/tree/pierremtb/issue3528-updater-tauri-to-electron
- https://github.com/KittyCAD/modeling-app/tree/cut-release-v0.25.0-updater-test-build-1
- https://github.com/KittyCAD/modeling-app/tree/cut-release-v0.25.0-updater-test-build-2

that the auto update flow worked as expected on macOS from tauri to electron build 1 to electron build 2

**Comment by pierremtb** [comment]
Smoke tested the whole updater loop: tauri to electron to electron + 1 on macOS and Windows, all looking good.

**Pull request merged**
