### PR TITLE
KCL |> pipelines cause Z-fighting

### PR DESCRIPTION
**Pull request by adamchalmers**
Currently pipeline expressions are causing some problem. You can see here that the two programs under tests/ are equivalent, just one uses pipelines and one always assigns to a new sketchgroup. However, the pipeline produces weird visual bugs.

closes https://github.com/KittyCAD/modeling-app/issues/1959
Closes https://github.com/KittyCAD/engine/issues/1941#issuecomment-2027907459

### CODE REVIEW

**Comment by adamchalmers** [comment]
@jessfraz I get a pretty different set of API requests from running the two programs (one that uses the |> syntactic sugar, one that desugars into assignments)

[desugar.txt](https://github.com/KittyCAD/modeling-app/files/14810081/desugar.txt)
[sugar.txt](https://github.com/KittyCAD/modeling-app/files/14810082/sugar.txt)

**Comment by adamchalmers** [comment]
Found and fixed the bug. My new execute_pipe_body was calling the first child expression twice. It should have read the second and following expressions from the `body_iter` but it actually read from `body`, so it read the first expression again.

Screenshot 2024-03-29 at 10 47 26 PM

**Review by jessfraz — APPROVED** [review]
I had also added a test for this main so likely that image needs updating as well, likely the cargo tests will fail idk tho 

anyways nice fix!

**Comment by mlfarrell** [comment]
I read this as Vulkan pipelines and my head exploded.  Lol.

**Pull request merged**
