### PR TITLE
Use ZOO_HOST not LOCAL_ENGINE_ADDR

### PR DESCRIPTION
**Pull request by adamchalmers**

### CODE REVIEW

**Review by jessfraz — APPROVED** [review]

**Comment by jessfraz** [comment]
man i feel like that should be a util maybe ill make a pr becuase that code is copied everywher

**Comment by jessfraz** [comment]
maybe we expose it to the world sincce i use the equivalent here too https://github.com/KittyCAD/kcl.py/blob/main/src/lib.rs#L185

**Comment by jessfraz** [comment]
ill make a pr

**Comment by adamchalmers** [comment]
@jessfraz OK feel free to close this one if you want

**Comment by jessfraz** [comment]
okay i made it way more dry and external folks can now call these like now we can use these in kcl.py https://github.com/KittyCAD/modeling-app/pull/4321

**Pull request closed without merging**
