### PR TITLE
Tag as top level construct 

### PR DESCRIPTION
**Pull request by jessfraz**
Now when you declare a tag on a function it starts with `$`
For example: `line([0,0], $myTag)`

And when you want to reference said tag later do this:
`startSketchOn(extrudeGroup, myTag)`

notice how initialization has a `$` but references do not.

cc @jgomez720 @r-barton @greg-kcio who write the most kcl

closes https://github.com/KittyCAD/modeling-app/issues/2389
closes https://github.com/KittyCAD/modeling-app/issues/2086

- [x] add to lsp symbols and add a test
- [x] add to lsp autocomplete and add a test
- [x] add a test for duplicate tags not being allowed
- [x] fix ts tests for new ast

After initial merge:
- [ ] add stdlib always parsing TagDeclarators
- [ ] make all js code mods make the new syntax
- [ ] add code mods to recast so we can easily update everyone's files
- [ ] migrate all tests and shit to new syntax
- [ ] after a few releases remove backwards compatibility

### CODE REVIEW

**Comment by jgomez720** [comment]
when this is in I'll update all the KCL examples

**Comment by jessfraz** [comment]
@jgomez720 im going to make it so recast will do it for you but you might have to verify its correct haha

**Comment by jgomez720** [comment]
ahh okay sweet

**Comment by jessfraz** [comment]
this is mostly the ast changes it is still backwards compatilbe. to prevent having to rebase, since these changes are huge i think i will merge this as part 1 with the changes above coming in part 2, no one needs to update their kcl as a part of part 1

**Comment by Irev-Dev** [comment]
CC @jtran just for interest/language changes

**Comment by Irev-Dev** [comment]
@jgomez720 just another little detail/quirk. Tag names will now need to conform to variable name constraints

I.e. "my-var", "my var" "235myVar" will not be valid, has to start with a letter, and cannot include spaces or hyphens.

**Pull request merged**
