### PR TITLE
Cut release v0.25.3

### PR DESCRIPTION
**Pull request by Irev-Dev**
## What's Changed
* Update app to sync with breaking change
* Implement from for unit length (#3932)
* Bump the world (kcl-lib) (#3930)
* Fix edge cut logic (#3928)
* Fix zoom callback on camera controls (#3924)
* zoom level increase when swapping sketch modes (#3854)
* Fix power syntax "4 ^ 2" (#3900)
* Bug fix: make dismiss during export not fire success toast (#3882)
* Fix canExtrudeSelectionItem and getSelectionType for multiple selections (#3884)
* Make light theme borders more contrasting, update sidebar icons (#3883)
* Fix: Opposite adjacent edge selection (#3896)

**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.25.2...v0.25.3

### CODE REVIEW

**Comment by Irev-Dev** [comment]
Manual testing Mac, `double click to open files from finder opens new window each time (mac/windows)` didn't work. would open but always the same window

**Comment by pierremtb** [comment]
Windows seemed good for:
open project
export STL
new project / sketch / extrude
sign out and sign back in
change a project setting

Still seeing the menu bar popping in as the cursor get close, we have an issue for that already I believe

**Comment by Irev-Dev** [comment]
I've been able to sanity check linux, can sign in, use the app and export stuff

But lots of the FS stuff and file association I couldn't do but not sure if that's because I'm a linux noob or not.

**Comment by Irev-Dev** [comment]
The playwright tests are all failing on text-to-cad, don't know why this broken all at once. Looking at the app, it's looks like it's simply not available in the command bar??

In a way this is good because it just being gone is slightly better than being there but very broken.

@pierremtb are thinking we really need to make this release because a couple of these quirks are still better than a totally bricked app.

**Comment by Irev-Dev** [comment]
Slack thread for more details.

**Comment by Irev-Dev** [comment]
I merged this, but as of yet have not published. With text to cad being very broken, I think rushing a release is probably not a good idea. We probably need to roll back (what must be the server side) PR that caused this.

**Pull request merged**
