### PR TITLE
Make engine background color driven by `theme` setting

### PR DESCRIPTION
**Pull request by franknoirot**
https://github.com/KittyCAD/modeling-app/assets/23481541/a9bf6cbe-ebdc-4bca-bfbb-6f872a4ec060

### CODE REVIEW

**Comment by franknoirot** [comment]
@Irev-Dev not critical work, but I think I'm just misunderstanding something that needs mocked in [MockEngineCommandManager](https://github.com/KittyCAD/modeling-app/blob/9fd99cb540e4f4310ff463785159ff62481c81d5/src/lib/testHelpers.ts#L11-L57) now that [I send an engineCommandManager command from SettingsAuthProvider](https://github.com/KittyCAD/modeling-app/pull/1842/files#diff-7fb9e612f9a90bd2659f3a68752689873240ddd5f7a28296252a931eeada8a85R101-R110)

**Comment by jessfraz** [comment]
this is fucking nice

**Comment by Irev-Dev** [comment]
> @Irev-Dev not critical work, but if you have any ideas I think I'm just misunderstanding something that needs mocked in [MockEngineCommandManager](https://github.com/KittyCAD/modeling-app/blob/9fd99cb540e4f4310ff463785159ff62481c81d5/src/lib/testHelpers.ts#L11-L57) now that [I send an engineCommandManager command from SettingsAuthProvider](https://github.com/KittyCAD/modeling-app/pull/1842/files#diff-7fb9e612f9a90bd2659f3a68752689873240ddd5f7a28296252a931eeada8a85R101-R110)

Oh so what happened here? or was this resolved by the circ-dep stuff?

**Review by Irev-Dev — APPROVED** [review]

**Comment by franknoirot** [comment]
> Oh so what happened here? or was this resolved by the circ-dep stuff?

Yup! I isolated the problem to find that it occurred even when I only added [this engine command to onEngineConnectionOpen](https://github.com/KittyCAD/modeling-app/pull/1842/files#diff-fd63f60bb0174079956c2dd9d8bcda72ba97b2bf47cca3948d47307a034c64e2R925-R937). My hypothesis is that adding the new imports from `lib/theme.ts` changed the order that the bundler loaded the singletons, maybe only in the Vitest testing environment, so the engineCommandManager wasn't instantiated in time for [these calls to `engineCommandManager.subscribeTo()`](https://github.com/KittyCAD/modeling-app/pull/1842/files#diff-865ed2d59a9612d99d8078219a01dbb9c6ae403201d0dd8565da69ea8acd61ab).

After your merge I was able to use `this.engineCommandManager.subscribeTo()`, removing the "maybe this doesn't exist right now even though tsc says it should?" hack, and the tests continued to pass!

**Pull request merged**
