### PR TITLE
Update onboarding based on team feedback

### PR DESCRIPTION
**Pull request by franknoirot**
Feedback on onboarding from user meeting with @JBEmbedded and friends

- [x]  links underline and different color
- [x] "Please give us feedback" link
- [x] Change KittyCAD to "Zoo"
- [x] Change from "Camera", it's not super clear. Maybe movement, or mouse, or view
- [x] Streaming video. Start with the why we're different. "Historically, CAD programs run on your computer."
- [x] Make the onboarding headings pop more
- [x] Stream text: Add a link to blog post
- [x] Check if we have usage telemetry
- [x] dimming is not effective in dark mode, make it more dramatic
- [x] "KCL is our own language", don't bury the lead.
- [x] KCL docs link on Text Editor page, but if you need blank, click the code menu
- [x] Change title for parametric modeling step to be less dramatic
- [x] Drawing in parametric makes JB think we can do assemblies, change that
- [x] `width` is on line 3
- [x] "Interactive numbers" not "Interactive Numbers"
- [x] use `<kbd>` elements and style them a different color
- [x] "*We believe* that editing code..."
- [x] Fix the last sentence, it's no longer true
- [x] Settings step, make it clear that we only have global settings right now
- [x] Zoo logo shortcut to home (in desktop)
- [x] When that change happens, also change the color or something to make it clickable separately
- [x] casing is wrong on gLTF
- [x] Link to David's talk
- [x] Export dialog should say where the file will be saved
- [x] Add description to fields like embedded
- [x] Links to feedback and Discord
- [x] Say how "w e'd love to see it", tag us on X

### CODE REVIEW

**Comment by franknoirot** [comment]
@Irev-Dev snapshots are updating because I tweaked the top bar to have a three-dot icon next to the project name and slightly different spacing between the logo and project name.

**Comment by franknoirot** [comment]
Gonna fix up whatever's wrong with the tests in the AM

**Comment by Irev-Dev** [comment]
The move camera tests failure is real, I was worried the test was flaky, but I can't move the camera at all on your branch.

**Comment by Irev-Dev** [comment]
> snapshots are updating because I tweaked the top bar to h...

btw, it's possible to tell playwright to snapshot a smaller part of the screen, so we could do that to stop this kind of thing from happening, but doesn't seem like that much of a PITA yet.

**Comment by franknoirot** [comment]
> The move camera tests failure is real, I was worried the test was flaky, but I can't move the camera at all on your branch.
>
> Maybe mouse events getting not making it to the canvas?

Thanks for taking a look @Irev-Dev, sorry you had to do that. I think I know why. I tried to update the default camera controls to "Zoo" from "KittyCAD" and I think I bet I didn't update it in the default settings

**Comment by franknoirot** [comment]
I reverted the setting to be called "KittyCAD", because my changes to allow fallback to default values when a settings has an invalid one [were in that reverted PR for file-based settings](https://github.com/KittyCAD/modeling-app/pull/1361), so if I change the setting's name now it'll break a lot of people's experiences. I'll prioritize the new settings work so that I can get that stuff back in and safely make the change.

**Pull request merged**
