### PR TITLE
Cut release v0.26.5

### PR DESCRIPTION
**Pull request by Irev-Dev**
## Fixed
* Fix bug where accepting an autocompletion would break the code editor (#4476)

**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.26.4...v0.26.5

### CODE REVIEW

**Comment by franknoirot** [comment]
### Smoke testing on Windows
- [ ] Mash keyboard in code editor
- [ ] https://github.com/KittyCAD/modeling-app/issues/3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [ ] https://github.com/KittyCAD/modeling-app/issues/3455
- [ ] https://github.com/KittyCAD/modeling-app/issues/3469
- [ ] https://github.com/KittyCAD/modeling-app/issues/3465
- [ ] double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [ ] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
- [ ] https://github.com/KittyCAD/modeling-app/issues/4038
- [ ] Move around and sketch rapidly: is interaction still snappy?

**Comment by Irev-Dev** [comment]
### MacOS

- [ ] Mash keyboard in code editor
- [ ] https://github.com/KittyCAD/modeling-app/issues/3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [ ] https://github.com/KittyCAD/modeling-app/issues/3455
- [ ] https://github.com/KittyCAD/modeling-app/issues/3469
- [ ] https://github.com/KittyCAD/modeling-app/issues/3465
- [ ] double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [ ] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
- [ ] https://github.com/KittyCAD/modeling-app/issues/4038
- [ ] Move around and sketch rapidly: is interaction still snappy?

**Comment by franknoirot** [comment]
Smoke testing passed on MacOS

**Review by franknoirot — APPROVED** [review]

**Comment by lf94** [comment]
Linux status: OK.

* [ ] Double clicking a KCL file opens ZMA. (N/A)
* [ ] The application opens
* [ ] User can sign in
* [ ] A project can be created (auto navigated for me)
* [ ] A sketch can be draw (line, arc, rect, circle).
* [ ] Lines and shapes can be modified.
* [ ] Select face and extruding works.
* [ ] Reloading the application reloads the sketch.
* [ ] Can create additional files and directories.
* [ ] Models can be exported to a file.
* [ ] I repeated some code done with point-and-click by typing in the code editor and everything was responsive and ok.
* [ ] The auto-updater works. (Currently broken as reported by Ryan and confirmed by myself but not a blocker)

**Pull request merged**
