### PR TITLE
Add message "click plane to sketch on" to toolbar after clicking start sketch

### LINKED ISSUE #2530: Start Sketch tools remain hidden while waiting for user to select plane
When you click "Start Sketch" and don't do anything, you end up seemingly stuck without any sketching tools. There are no instructions indicating what to do next.

Screenshot 2024-05-24 at 5 55 16 PM

The UI is waiting for you to select a plane to sketch on. Now that we've implemented zoom to fit, I guess I have been doing less arbitrary clicks which would have automatically led me to click _somewhere_ just to be able to see what's going on. We should let the user know what they are expected to do after "Start Sketch" and should probably consider showing the sketch tools as soon as the user clicks. Then we can handle manage user expectations while they have the tools they expect to be there which might not yet be usable due to some condition like "select a plane".

### PR DESCRIPTION
**Pull request by dshaw**
I'm proposing explicitly using the callout to click to make the intent explicit.

Screenshot 2024-06-04 at 1 32 33 AM

Fixes #2530

### CODE REVIEW

**Comment by dshaw** [comment]
@franknoirot If you agree with the strategy of injecting this message into the toolbar (for now), I think this could use some styling. Any classes you think might be useful here?

**Comment by franknoirot** [comment]
> @franknoirot If you agree with the strategy of injecting this message into the toolbar (for now), I think this could use some styling. Any classes you think might be useful here?

I'm not keen to change the color or add a background/border to it, because those default colors are the highest contrast you're going to get without looking like a button. I would suggest a little bit of horizontal breathing room with `mx-2`, and maybe bump the font down to `text-sm`. Our button text is `text-xs` but I think it's good that this message is a bit bigger.

**Comment by dshaw** [comment]
@franknoirot I think that's perfect. Wrapped everything in a div. Don't know if we have any philosophical objects to divs, so calling that out.

Screenshot 2024-06-04 at 9 48 14 AM

**Comment by franknoirot** [comment]
> Don't know if we have any philosophical objects to divs, so calling that out.

Not for this use case!

**Review by franknoirot — APPROVED** [review]

**Comment by lf94** [comment]
Can we merge this

**Pull request merged**
