### PR TITLE
Lf94/eco mode save the planet

### PR DESCRIPTION
**Pull request by lf94**
The stream is torn down after 20s.

The teardown happens when:

* browser tab is changed
* browser window is minimized
* no input from any device in 20s.

Instead of a canvas, pausing the video keeps the last frame :)

https://github.com/KittyCAD/modeling-app/assets/547923/0d8f8618-0653-429d-ae03-aa95dfaf1043

also include proper shutdown for tests

Related to https://github.com/KittyCAD/modeling-app/issues/563

### CODE REVIEW

**Comment by Irev-Dev** [comment]
Danger :)

**Comment by Irev-Dev** [comment]
How well does this work when you in sketch mode? does it put you back into sketch mode okay?

**Comment by lf94** [comment]
> How well does this work when you in sketch mode? does it put you back into sketch mode okay?

You know I never tried, lol.

**Comment by jessfraz** [comment]
putting you back into sketch mode hard, but at least does it exit you out nicely when you come back

**Comment by Irev-Dev** [comment]
> but at least does it exit you out nicely when you come back

Yeah I'm fine with this.

**Comment by lf94** [comment]
Everything passed and there are 2 false positives on macos so if can force merge that'd be great :) (I had to rebase but I'm not going to bother re-running ubuntu playwright again 2-3x).

**Comment by Irev-Dev** [comment]
@lf94 those are not false positives, the `emulateNetworkConditions` stuff only works for chrome, and macos runs on webkit.

I'll update that test to only run on chrome.

I'm getting the exact same failures on https://github.com/KittyCAD/modeling-app/pull/2956

**Comment by lf94** [comment]
@Irev-Dev those tests should actually work now but for some reason they aren't; I say that because I added a window.tearDown which it should be calling now

**Comment by Irev-Dev** [comment]
@lf94, I don't see how they could possibly work when this is in `test-utils.ts`
image

**Comment by lf94** [comment]
Because of 

```
      if (cdpSession === null) {
        // Use a fail safe if we can't simulate disconnect (on Safari)
        return page.evaluate('window.tearDown()')
      }
```

Since simulated disconnect doesn't work in Safari

---

Frank ended up just reverting them to skip for now; we can try to fix again later :)

**Comment by Irev-Dev** [comment]
Ah okay, 
So I should close out https://github.com/KittyCAD/modeling-app/pull/2957?

**Comment by Irev-Dev** [comment]
I don't see his PR

**Comment by lf94** [comment]
@franknoirot

**Pull request merged**
