### PR TITLE
Handle the case of no avatar

### PR DESCRIPTION
**Pull request by lf94**
Closes https://github.com/KittyCAD/modeling-app/issues/2939

### CODE REVIEW

**Comment by franknoirot** [comment]
Only question I have is why all the test snapshots now show the kitten avatar? Probably not a big deal I'm just not grokking the test-only kitten avatar logic

**Comment by lf94** [comment]
> Only question I have is why all the test snapshots now show the kitten avatar? Probably not a big deal I'm just not grokking the test-only kitten avatar logic

Huh that should've been the case before.

**Review by franknoirot — APPROVED** [review]
Oh it might not have tripped the snapshot tests before. Test looks good

**Comment by lf94** [comment]
Fixing this up now

**Pull request merged**
