### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nrc**
Update README.md to make it accurate and fix a few typos. Also removes a file which looks like command line output which was committed accidentally.

### CODE REVIEW

**Review by franknoirot — APPROVED** [review]
LGTM, I just merged in main to get another swing at CI, the failures seem spurious.

**Comment by jtran** [comment]
@franknoirot hypothesized that the reason why CI is failing is because you're using your own fork of the repo. None of us do that. We'd like to get this working, but I just wanted to let you know what the hold-up is.

**Comment by nrc** [comment]
> @franknoirot hypothesized that the reason why CI is failing is because you're using your own fork of the repo. None of us do that. We'd like to get this working, but I just wanted to let you know what the hold-up is.

Oh, do you push a branch to `KittyCAD/modeling-app` to make a PR?

**Comment by jtran** [comment]
Yes, that's how we usually do it.

**Comment by nrc** [comment]
Closing in favour of https://github.com/KittyCAD/modeling-app/pull/4130

**Pull request closed without merging**
