### PR TITLE
Cut release v0.15.5

### PR DESCRIPTION
**Pull request by Irev-Dev**
- [Clean up possibly dead code](https://github.com/KittyCAD/modeling-app/pull/1032)
- [fix error sourcce range for kcl stdlib ](https://github.com/KittyCAD/modeling-app/pull/1641)
- [make export e2e test more robust](https://github.com/KittyCAD/modeling-app/pull/1638)
- [Fillets](https://github.com/KittyCAD/modeling-app/pull/1401)
- [Bump KCVM](https://github.com/KittyCAD/modeling-app/pull/1631)
- [Increase playwright timeout on a per test basis](https://github.com/KittyCAD/modeling-app/pull/1627)
- [update discord announce under 2000 char limit](https://github.com/KittyCAD/modeling-app/pull/1628)
- [Add export to cmd bar](https://github.com/KittyCAD/modeling-app/pull/1593)
- [undo test stuff](https://github.com/KittyCAD/modeling-app/pull/1619)
- [make close segment visually distinct](https://github.com/KittyCAD/modeling-app/pull/1620)
- [remove playwright parallel, but run macos and ubuntu at the same time](https://github.com/KittyCAD/modeling-app/pull/1617)
- [clean up old snapshot images](https://github.com/KittyCAD/modeling-app/pull/1618)
- [snap to profile start](https://github.com/KittyCAD/modeling-app/pull/1616)
- [Remove unnecessary import](https://github.com/KittyCAD/modeling-app/pull/1611)
- [Refactor client scene mouse event args](https://github.com/KittyCAD/modeling-app/pull/1613)
- [Grackle: stdlib LineTo function](https://github.com/KittyCAD/modeling-app/pull/1601)
- [unused vars cleanup](https://github.com/KittyCAD/modeling-app/pull/1608)
- [add test: Can edit segments by dragging their handles](https://github.com/KittyCAD/modeling-app/pull/1607)
- [show selected color for start selected at](https://github.com/KittyCAD/modeling-app/pull/1606)
- [Grackle: lineTo stdlib function](https://github.com/KittyCAD/modeling-app/pull/1605)
- [fully remove show](https://github.com/KittyCAD/modeling-app/pull/1592)
- [try parallel plawright](https://github.com/KittyCAD/modeling-app/pull/1579)
- [make kcl std lib first class](https://github.com/KittyCAD/modeling-app/pull/1603)
- [make startProfileAt UI editable](https://github.com/KittyCAD/modeling-app/pull/1599)
- [Implement dual camera sync direction](https://github.com/KittyCAD/modeling-app/pull/1597)
- [import docs](https://github.com/KittyCAD/modeling-app/pull/1602)
- [EngineConnection should fail fast if socket closes](https://github.com/KittyCAD/modeling-app/pull/1600)
- [failing auto complete test](https://github.com/KittyCAD/modeling-app/pull/1578)
- [enable concurrency for playwright action](https://github.com/KittyCAD/modeling-app/pull/1598)
- [Refactor: move point-parsing into its own function](https://github.com/KittyCAD/modeling-app/pull/1590)
- [one more sentry](https://github.com/KittyCAD/modeling-app/pull/1591)

### CODE REVIEW

**Comment by pierremtb** [comment]
Re-running `playwright-ubuntu`

**Comment by pierremtb** [comment]
Failed three times in a row 😞

**Comment by Irev-Dev** [comment]
I just restarted virginia engine-api, too many "loading" failures.

**Comment by pierremtb** [comment]
Thank you @Irev-Dev!

**Pull request merged**
