### PR TITLE
Cut release v0.26.1

### PR DESCRIPTION
**Pull request by lf94**
## What's Changed
* Disable rotate on start new sketch (#4287)
* Stop propagation of camera clicks after drags (#4257)
* Rename Sketch.value to Sketch.paths (#4272)
* Fix engine connection break when starting onboarding from a fresh install (#4263)
* Support negative start and end in ranges (#4249)
* Remove setInterval implementations from camera controls (#4255)
* Fix job name for printers (#4234)
* Buffer file writes, because writing to file after every keypress has bad consequences (#4242)

**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.26.0...v0.26.1

### CODE REVIEW

**Review by franknoirot — APPROVED** [review]
Patch release makes sense

**Comment by franknoirot** [comment]
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, mod + shift + .)
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
- [ ] If someone at the office, test you can hit make from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [ ] Electron tests: ensure we can open files that in tauri we would not be able to #3455 
- [ ] Electron test: upgrading app should not cause user to have to auth again #3469
- [ ] Electron: logging in and authing works #3465
- [ ] double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [ ] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
- [ ] Token.txt should work #4038

**Comment by lf94** [comment]
## Linux cleared

### Manual Tasks
- [x] Mash keyboard in the code editor
- [x] https://github.com/KittyCAD/modeling-app/issues/3373
- [x] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
- [x] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [x] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [x] Test updating versions works
- [x] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [x] https://github.com/KittyCAD/modeling-app/issues/3455
- [x] https://github.com/KittyCAD/modeling-app/issues/3469
- [x] https://github.com/KittyCAD/modeling-app/issues/3465
- [ ] double click to open files from finder opens new window each time (mac/windows)
- [x] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [x] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
- [x] https://github.com/KittyCAD/modeling-app/issues/4038

**Comment by franknoirot** [comment]
Updater test on Mac passed after reverting #4270  and updating the release branch.

**Pull request merged**
