### PR TITLE
Fix code editor user input in older version of Safari

### PR DESCRIPTION
**Pull request by nilpunning**
Understandably `user-select:none` is applied to one of the top level divs of the entire user interface, but in older versions of Safari this prevents typing input by the user.  This change will reset `user-select` to the default for the code mirror editor.  It doesn't appear to cause problems in code mirror or with other browsers.  This issue may be related to this webkit bug: https://bugs.webkit.org/show_bug.cgi?id=82692.

### CODE REVIEW

**Comment by jessfraz** [comment]
thank you for this and your first contribution, sorry for the delay!

**Comment by jessfraz** [comment]
i think this is breaking the playwright tests?

**Comment by jessfraz** [comment]
I think this isnt on you I think its due to secrets and it being a fork, will let @franknoirot try out locally and merge if fine

**Comment by franknoirot** [comment]
Yeah @jessfraz I've confirmed that running the playwright test suite locally with a dev token passes just fine. Thanks for contributing @nilpunning, good catch!

**Review by franknoirot — APPROVED** [review]
Thanks for the thorough documentation in your PR I didn't know about this WebKit issue!

**Pull request merged**
