### PR TITLE
Make application aware it saved the buffer and not something else

### PR DESCRIPTION
**Pull request by lf94**
Only pinging you jess in case Frank's out for the weekend

It solves the issue coreypdx reported on discord: https://discord.com/channels/915388055236509727/1299168400479748097

### CODE REVIEW

**Review by franknoirot — APPROVED** [review]
Makes sense, also this is our longest property name so far 🏆

**Comment by lf94** [comment]
Yeah I only did it so we 100% know where it is used

**Review by jessfraz — APPROVED** [review]

**Comment by jessfraz** [comment]
a playwirght test would be nice for making sure this doesnt regress

**Comment by jessfraz** [comment]
its weird playwright didnt catch this before mayube we slow down typing for a test
or maybe we have no desktop tests that actually type in the editor

**Comment by franknoirot** [comment]
> its weird playwright didnt catch this before mayube we slow down typing for a test or maybe we have no desktop tests that actually type in the editor

We've been using [Playwright's `.fill` method](https://playwright.dev/docs/api/class-locator#locator-fill), but maybe we can change a test that would capture this to use [the `.pressSequentially` method](https://playwright.dev/docs/api/class-locator#locator-press-sequentially).

**Comment by lf94** [comment]
This one wouldve been caught with a simple manual test, I added it to our list earlier in the week

**Pull request merged**
