### PR TITLE
Cut release v0.25.6

### PR DESCRIPTION
**Pull request by nadr0**
## What's Changed
  * KCL: No 'let' or 'const' keyword required when declaring vars (#4063)
  * KCL: new standard library 'map' function (#4054)
  * KCL: If-else expressions (#4022)
  * Add menu item and hotkey to center view on current selection (#4068)
  * KCL: Reduce can take and return any KCL values (#4094)
  * File tree and projects now reload when there are external changes on the file system (#4077)
  * and many more bug fixes and improvements

  **Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.25.5...v0.25.6

### CODE REVIEW

**Comment by nadr0** [comment]
Grab the `out-ubuntu-22.04` AppImage from the `build-publish-apps` job in the CI CD pipeline of the PR that has the cut release. [Example](https://github.com/KittyCAD/modeling-app/actions/runs/11111096304) scroll to the bottom and see the artifacts sections to download the file.

> Gotcha: I had to `chmod +x` the file and install Fuse to get the AppImage running

> Use: updater-test-ubuntu-22.04 from the artifacts page for the update tests. 

- [ ] Electron tests: external links open an external browser #3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
  - [ ] !
  - [ ] Bug bottom folder page
  - [ ] Bug bottom model render page
  - [ ] :heavy_exclamation_mark: (Does not work on linux) mod + shift + .
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default/cube.kcl
```
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
  - [ ] Opens directory
  - [ ] Creates main file if empty

```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default
```

```
rm /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty/main.kcl

/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty
```
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
    - [ ] xx.xx
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default/chassis-with-rails.kcl
```
- [ ] Electron tests: ensure we can open files that in tauri we would not be able to #3455  
  - [ ] Opening file
  - [ ] Editing file
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/smoke-test-file-permissions-linux/main.kcl
```
- [ ] Electron test: upgrading app should not cause user to have to auth again #3469 issues/3469
- [ ] Electron: logging in and authing works #3465 
- [ ] :heavy_exclamation_mark: (Does not work on Linux) double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)

**Notes**
- Opening a path to a directory that doesn't exist, hangs, should we create the directory?
```
Loading project at startup: /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty-2
Error: ENOENT: no such file or directory, stat '/home/kevin-nadro/Documents/zoo-modeling-app-projects/empty-2'
[42821:0930/142409.906556:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Checking for update
Update for version 0.25.5 is not available (latest version: 0.25.4, downgrade is disallowed).
```
- Cannot figure out mod + shift + . on linux for core dump
- Double clicking files on linux does not work.

**Comment by franknoirot** [comment]
```[tasklist]
### Windows manual tests (from #3588)
- [ ] https://github.com/KittyCAD/modeling-app/issues/3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [ ] https://github.com/KittyCAD/modeling-app/issues/3455
- [ ] https://github.com/KittyCAD/modeling-app/issues/3469
- [ ] https://github.com/KittyCAD/modeling-app/issues/3465
- [ ] double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [ ] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
- [ ] https://github.com/KittyCAD/modeling-app/issues/4038
```

**Comment by nadr0** [comment]
A note, the auto updater for linux x64 did not get generated and uploaded so I cannot test this workflow. We will need to figure out why it was not uploaded.

**Comment by lf94** [comment]
Grab the `out-ubuntu-22.04` AppImage from the `build-publish-apps` job in the CI CD pipeline of the PR that has the cut release. [Example](https://github.com/KittyCAD/modeling-app/actions/runs/11111096304) scroll to the bottom and see the artifacts sections to download the file.

> Gotcha: I had to `chmod +x` the file and install Fuse to get the AppImage running

> Use: updater-test-ubuntu-22.04 from the artifacts page for the update tests. 

- [ ] Electron tests: external links open an external browser #3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
  - [ ] !
  - [ ] Bug bottom folder page
  - [ ] Bug bottom model render page
  - [ ] :heavy_exclamation_mark: (Does not work on linux) mod + shift + .
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default/cube.kcl
```
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
  - [ ] Opens directory
  - [ ] Creates main file if empty

```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default
```

```
rm /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty/main.kcl

/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty
```
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
    - [ ] xx.xx
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default/chassis-with-rails.kcl
```
- [ ] Electron tests: ensure we can open files that in tauri we would not be able to #3455  
  - [ ] Opening file
  - [ ] Editing file
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/smoke-test-file-permissions-linux/main.kcl
```
- [ ] Electron test: upgrading app should not cause user to have to auth again #3469 issues/3469
- [ ] Electron: logging in and authing works #3465 
- [ ] :heavy_exclamation_mark: (Does not work on Linux) double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)

**Notes**
- Opening a path to a directory that doesn't exist, hangs, should we create the directory?
```
Loading project at startup: /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty-2
Error: ENOENT: no such file or directory, stat '/home/kevin-nadro/Documents/zoo-modeling-app-projects/empty-2'
[42821:0930/142409.906556:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Checking for update
Update for version 0.25.5 is not available (latest version: 0.25.4, downgrade is disallowed).
```
- Cannot figure out mod + shift + . on linux for core dump
- Double clicking files on linux does not work.

**Comment by pierremtb** [comment]
Updater test checked on Windows and macOS

**Review by pierremtb — APPROVED** [review]

**Comment by franknoirot** [comment]
Vercel is having a partial outage right now with their Builds Queue, resulting in a hanging check here that I have to override to release. https://www.vercel-status.com/incidents/sxfvdhf3zxsq

**Pull request merged**
