### PR TITLE
Add lsystem.kcl to tests

### PR DESCRIPTION
**Pull request by lf94**

### CODE REVIEW

**Review by jessfraz — APPROVED** [review]

**Comment by lf94** [comment]
I think the test is genuinely choking on the new KCL? Does that mean we keep this unmerged?

**Comment by jtran** [comment]
It bothers me that cargo test isn't a required check.

Are you able to get the test to pass if you run it locally?

**Comment by lf94** [comment]
Locally I'm getting a lot of failures unrelated to my addition - I tried an API key from both prod and dev - am I missing something? This is how I'm running it (copied from the CI):

```
 KITTYCAD_API_TOKEN="api-xxxxx" cargo llvm-cov --all --lcov --output-path lcov.info --no-fail-fast
 ```

**Comment by lf94** [comment]
Need some help on this one because I cannot reproduce the same single failure locally.

**Comment by lf94** [comment]
I guess I need to turn down the iterations.

**Pull request merged**
