### PR TITLE
fix: only count something as a directory if it has children

### LINKED ISSUE #4515: [BUG]: The count of number of folders when displayed on the project page is incorrect.
### Describe the bug

The display for the number of folders on the main page is incorrect. 

### Steps to Reproduce

1. Boot the application
2. Go to the project selection page
3. Look at the files/folder count
4. See that the folder count is incorrect. 

### Expected Behavior

The folder count should count the number of folders within that directory. 

### Screenshots and Recordings

Image

Default says 20 files / 19 folders

Image
Inside it only has 3 folders. 

### Desktop OS

Ubuntu 22.04 Linux

### Browser

_No response_

### Version

v0.26.5

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jtran**
Replaces #4556. Working around CI limitation.
Closes #4515.

### CODE REVIEW

**Comment by TomPridham** [comment]
I also just pushed a change to my branch that updates the e2e tests in the `file-tree-spec` since they were expecting the old behavior

**Comment by TomPridham** [comment]
Oh, so, this line is never resolving because the span with that test id doesn't get rendered if there are 0 folders
https://github.com/KittyCAD/modeling-app/blob/main/e2e/playwright/fixtures/homePageFixture.ts#L67

**Comment by TomPridham** [comment]
There aren't currently any tests actually using the folder count, so deleting it would be an option. I did push another fix that I _think_ would fix it. I can't actually run the e2e tests based on the info in the readme afaik

**Comment by jtran** [comment]
If it doesn't work, I think removing the folder count from the helper and only using it where we explicitly want to assert the value is a good option.

**Review by pierremtb — APPROVED** [review]
Thanks @TomPridham and @jtran!

**Pull request merged**
