### PR TITLE
Better styling for pane and KCL editor focus

### LINKED ISSUE #2669: Code editor is not clearly focused when available to type

### PR DESCRIPTION
**Pull request by franknoirot**
Hopefully resolves #2669 by doing the following:
1. Updating the borders of sidebar pane when focus enters and exits it
2. Updating pane background when focus enters/exits it, nearly opaque with focus within it
3. Not showing a cursor in the KCL editor if focus is not within it
4. Making the active line styling in the KCL editor receives and loses focus
5. Making the matching brace styling less opaque so the cursor is easier to see

## Demo

https://github.com/KittyCAD/modeling-app/assets/23481541/988e5589-2d03-4bda-bd5f-22d30b13275d

### CODE REVIEW

**Comment by lf94** [comment]
Fantastic improvements! Could I request or suggest one more (feel free to reject)? On editor selection, the background is less transparent? Maybe even mostly opaque?

**Comment by franknoirot** [comment]
That's a great idea

**Comment by franknoirot** [comment]
I went with 90% opacity when focus is within. With the background blur I think it leaves just a hint of presence of the scene behind, but it's still way more readable than the 50% we had (and still have when focus isn't within the pane).

**Comment by lf94** [comment]
Exactly what I had in mind :)

**Pull request merged**
