### PR TITLE
turning back on all planes

### PR DESCRIPTION
**Pull request by jessfraz**
https://github.com/KittyCAD/modeling-app/assets/1445228/601060d1-1837-4c17-819f-16c972fd23a0

closes https://github.com/KittyCAD/modeling-app/issues/538

This will make `startSketchAt` still work but default to the 'xy' plane, until I can do a follow up PR with code mods, I have ideas for it but this PR is already huge so want to split it out.

- [x] add `startSketchOn` fn
- [x] add `startProfileAt` fn
- [x] error when using `startProfileAt` and sketch not closed
- [x] call disable sketchMode on `close` in executor
- [x] update all tests and sample code
- [x] update modifyAst ts files so this work
- [x] make move lines work with this
- [x] reset camera after disable sketch mode/ or way to not make camera move on sketch mode https://github.com/KittyCAD/engine/issues/1466
- [x] pass in the actual planes we are on to modifyAst (ts) and movelines (rust) see Stream.tsx
- [x] pass in default plane ids to rust side, executor so we don't recreate them
- [x] hide planes by default
- [x] in edit sketch mode, figure out the plane we are on from the code https://github.com/KittyCAD/modeling-app/blob/main/src/hooks/useAppMode.ts#L61
- [x] get normals to work correctly on click in sketch mode click-and-point
- [x] https://github.com/KittyCAD/engine/issues/1471
- [x] tests for different planes and negative planes
- [x] use new kittycad.rs lib
- [x] use new kittycad.ts lib
- [x] try to prevent flicker of plane creation on initial load
- [x] editing a sketch should be on the correct plane

### CODE REVIEW

**Comment by jgomez720** [comment]
Uploading Screenshare - 2023-10-04 1_05_14 PM.mp4…

```
const sigmaAllow = 15000 // psi
const width = 11 // inch
const p = 150 // Force on shelf - lbs
const distance = 12 // inches
const FOS = 2
const thickness = sqrt(distance * p * FOS * 6 / (sigmaAllow * width))
const filletR = thickness * 2
const shelfMountL = 9
const wallMountL = 8

const bracket = startSketchOn('XY')
  |> startProfileAt([0, 0], %)
  |> line([0, wallMountL], %)
  |> tangentalArc({ radius: filletR, offset: 90 }, %)
  |> line([-shelfMountL, 0], %)
  |> line([0, -thickness], %)
  |> line([shelfMountL, 0], %)
  |> tangentalArc({
       radius: filletR - thickness,
       offset: -90
     }, %)
  |> line([0, -wallMountL], %)
  |> close(%)
  |> extrude(width, %)

show(bracket)
const part001 = startSketchOn('XY')
  |> startProfileAt([-13.71, 5.46], %)
  |> line([10.44, -0.04], %)
  |> line([-0.09, -8.65], %)
  |> line([-10.79, 0.17], %)
  |> close(%)
  |> extrude(4, %)
const part002 = startSketchOn('-YZ')
  |> startProfileAt([-10.78, 15.76], %)
  |> line([-14.29, 0.24], %)
  |> line([9.06, -11.67], %)
  |> close(%)

```

**Comment by mlfarrell** [comment]
unrelated to debugging the plane side:  the planes popup and dissapear right when the web app loads now.   i'd consider this a bug.

**Comment by jessfraz** [comment]
@mlfarrell yeah its the time difference between we create and we hide was going to add an optioin on MakePlane to hide initally to avoid the extra websocket call

**Comment by jgomez720** [comment]
https://github.com/KittyCAD/modeling-app/assets/114548659/d17685ea-6dae-4474-b886-0d717d8e3866

```
const sigmaAllow = 15000 // psi
const width = 11 // inch
const p = 150 // Force on shelf - lbs
const distance = 12 // inches
const FOS = 2
const thickness = sqrt(distance * p * FOS * 6 / (sigmaAllow * width))
const filletR = thickness * 2
const shelfMountL = 9
const wallMountL = 8

const bracket = startSketchOn('XY')
  |> startProfileAt([0, 0], %)
  |> line([0, wallMountL], %)
  |> tangentalArc({ radius: filletR, offset: 90 }, %)
  |> line([-shelfMountL, 0], %)
  |> line([0, -thickness], %)
  |> line([shelfMountL, 0], %)
  |> tangentalArc({
       radius: filletR - thickness,
       offset: -90
     }, %)
  |> line([0, -wallMountL], %)
  |> close(%)
  |> extrude(width, %)

show(bracket)
const part001 = startSketchOn('XY')
  |> startProfileAt([-15.53, -10.28], %)
  |> line([10.49, -2.08], %)
  |> line([10.42, 8.47], %)
  |> line([-19.16, 5.1], %)
  |> close(%)
  |> extrude(4, %)

const part002 = startSketchOn('-XZ')
  |> startProfileAt([-9.35, 19.18], %)
  |> line([32.14, -2.47], %)
  |> close(%)
const part003 = startSketchOn('-XZ')
  |> startProfileAt([13.82, 16.51], %)
  |> line([-6.24, -30.82], %)
  |> close(%)
const part004 = startSketchOn('YZ')
  |> startProfileAt([19.04, 20.22], %)
  |> line([9.44, -30.16], %)
  |> close(%)

```

**Comment by jessfraz** [comment]
as discussed on slack seems like the codegen was delayed which is sometimes reproducable sometimes not but like those parts are not really valid since its missing a line segment... anyways worth trying again, likely just the dev instances being slow and codegen being slow

**Pull request merged**
