### PR TITLE
show default planes on empty scene

### LINKED ISSUE #2880: Show default planes when scene is empty
When the user has nothing in the scene, show some default planes to give them a way to orient themselves. Here is a goal of how we would like the planes to eventually look, although they can use their current styling for now[^1]:

view of the app with an empty scene, showing 3 labeled default planes

[^1]: See [this Figma flow](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=3231-32156&t=PQBIJPfroQjQZGTa-11) for that mockup in the broader context

### PR DESCRIPTION
**Pull request by Irev-Dev**
Closes #2880

Diff is large on this one because there were tentatively related clean-up tasks.

I haven't thoroughly tested it, but there are two things you should know:

There's an existing issue where the engine's auto scale of the default planes breaks really easily resulting in the default planes being too big (demo by showing planes on load, adding something to the scene to make them hid again, then emptying the scene to show the giant planes)

https://github.com/user-attachments/assets/eda4df9a-6714-4859-9c3c-b80f5deeeddb

I made the planes not react to hovers until the user actually hits start sketch this feels pretty natural as orientation purposes only

https://github.com/user-attachments/assets/950acb57-0f04-4781-aa6d-f64fbf22484b

CC @jessfraz, I'll try and guide this to a merge and release tomorrow, but I'm not at home so it might be a bit slow.

### CODE REVIEW

**Comment by Irev-Dev** [comment]
In https://github.com/KittyCAD/modeling-app/pull/3237/commits/a2be3bdb9e2ab6feb284bc302a1457ce00eb432f there are three tests that are consistently failing, so they are probably real.
I'll look at them in my morning.

**Comment by Irev-Dev** [comment]
Okay I stayed up a bit later, hope I fixed them

**Review by paultag — APPROVED** [review]

**Comment by franknoirot** [comment]
Just pulled it down and tried to break it, and I couldn't. Nice way to go man

**Comment by paultag** [comment]
@franknoirot what do you say, should we ship it?

**Comment by Irev-Dev** [comment]
Added a test for this too in https://github.com/KittyCAD/modeling-app/pull/3249

**Pull request merged**
