### PR TITLE
Fix NetworkMachineIndicator and machines dynamically showing in CommandBar

### PR DESCRIPTION
**Pull request by lf94**

### CODE REVIEW

**Review by jessfraz — APPROVED** [review]

**Comment by jessfraz** [comment]
at some point would be dope to test against the mock here cc @paultag

**Comment by jessfraz** [comment]
esp since we keep adding more and more complexity

**Comment by lf94** [comment]
Yeah! and because it's fairly light weight (right?) we should be able to just spin it up beside the web app in the CI tests

**Comment by paultag** [comment]
Yeah absolutely - it's why I made the Noop machine -- will get to chipping at test scenarios so we can write tests against the populated path (e.g. idle, error string, running, percentage, etc)

**Pull request merged**
