### PR TITLE
Add keyboard shortcuts for sketch and modeling tools

### PR DESCRIPTION
**Pull request by franknoirot**
closes https://github.com/KittyCAD/modeling-app/issues/2442

They are only available if the toolbar is on the screen and the user isn't in a form or contenteditable field (like the CodeMirror editor). This is a rough implementation before we get a full keymap system laid out, but just so people can start getting muscle memory for the basic shortcuts in the mean time.

## Demo

https://github.com/KittyCAD/modeling-app/assets/23481541/5b35f5b2-9186-46cf-8291-c8dbb9d86ed6

### CODE REVIEW

**Comment by jessfraz** [comment]
I feel like at some point (doesnt have to be now) we are going to want to move all the keybindings into a single fine, that has an interface that works for both codemirror and outside codemirror, its really hard right now to tell "is this keybinding already taken" since they sprawl across lots of files

**Review by Irev-Dev — APPROVED** [review]
This looks good

Re: Jess's comment going forward it would be good to be able to centralise things.

I had thought the more we have in xstate, we can just have our buttons, command bar actions and hotkeys just firing the same xstate events, maybe that doesn't work so well with the command bar since it runs it's own child state, I don't have a firm grasp how those things might work.

One other thought in relation to this PR is maybe we can tweak our state digrame so that equip actions also work the same as cancel so that
```typescript
useHotkeys(
    'l',
    () =>
      state.matches('Sketch.Line tool')
        ? send('CancelSketch')
        : send('Equip Line tool'),
    { enabled: !disableAllButtons, scopes: ['sketch'] }
  )
  ```
  
Can become
```typescript
useHotkeys(
    'l',
    () => send('Equip Line tool'),
    { enabled: !disableAllButtons, scopes: ['sketch'] }
  )
  ```
  
That is push more logic into xstate and make the hotkeys really dumb.

**Comment by franknoirot** [comment]
> I feel like at some point (doesnt have to be now, but sooner rather than later) we are going to want to move all the keybindings into a single file, that has an interface that works for both codemirror and outside codemirror, its really hard right now to tell "is this keybinding already taken" since they sprawl across lots of files

Absolutely, that's what the in-progress work in my franknoirot/editable-hotkeys branch is aiming to do. That branch has an XState machine that lower components can register interaction map items to (trying to find a more generic term than key map since they can include mouse interactions too). This is just a quick win that'll get solidified, made into a key map layer, and made editable in the PR.

**Comment by franknoirot** [comment]
> I had thought the more we have in xstate, we can just have our buttons, command bar actions and hotkeys just firing the same xstate events, maybe that doesn't work so well with the command bar since it runs it's own child state, I don't have a firm grasp how those things might work.

Yeah I'd like that too! Some of our modeling commands are direct (like Srart sketch) and others leverage the command bar to get extra data (like Extrude) so I think some of that needs streamlined but that's already the case for the Toolbar without these shortcut keys.

> One other thought in relation to this PR is maybe we can tweak our state digrame so that equip actions also work the same as cancel...

Nice I'd like that. I wish Xstate let you more easily define a state toggle without doubling every event. Like just flagging an event as bidirectional somehow.

**Comment by jessfraz** [comment]
Needs playwright tests

**Comment by franknoirot** [comment]
> Needs playwright tests

(playw)right, thanks on it

**Pull request merged**
