### PR TITLE
Remove just one enum

### PR DESCRIPTION
**Pull request by adamchalmers**
# Problem

This is my proposal for fixing #1107 . I've only done it for one stdlib function, `tangentialArcTo` -- if y'all like it, I'll apply this idea to the rest of the stdlib.

Previously, if users want to put a tag on the arc, the function's parameters change type.

```
// Tag missing: first param is array
tangentialArcTo([x, y], %)
// Tag present: first param is object
tangentialArcTo({to: [x, y], tag: "myTag"}, %)
```

# Solution

My proposal in #1006 is that KCL should have optional values. This means we can change the stdlib `tangentialArcTo` function to use them. In this PR, the calls are now like

```
// Tag missing: first param is array
tangentialArcTo([x, y], %)
// Tag present: first param is array still, but we now pass a tag at the end.
tangentialArcTo([x, y], %, "myTag")
```

This adds an "option" type to KCL typesystem, but it's not really revealed to users (no KCL types are revealed to users right now, they write untyped code and only interact with types when they get type errors upon executing programs). Also adds a None type, which is the default case of the Optional enum.

### CODE REVIEW

**Comment by jessfraz** [comment]
sounds good to me if @Irev-Dev  is good with it!

**Comment by Irev-Dev** [comment]
Yeah sounds good to me.

Adam and I had a chat earlier as to whether data-last was worth clinging to, but we don't think so.

The only yellow flag I want to throw up is that there are ast-mods that will need to change for this. but I'm happy to tackle the second half of the PR to fix that up.

**Comment by paultag** [comment]
As a general philosophy I really like the idea of as little as possible existing as a built-in, and building as much as we can using the language itself. I like the idea of variadic functions (so long as we document, autocomplete, and are able to statically lint) so this all def seems cool by my eye. I reckon it may even help with discoverability and readability, since the function that "does the thing" will have a number of different documented definitions for variations on a theme.

Removing this function would be a breaking change  -- abet not a super disruptive one since we've made no stability promises in our preview builds, so now's the time to do this type of stuff before the equities become more complex and we have to more seriously consider language stability (yes the irony given my popoff on API/ABI stability holding projects back generally yesterday is not lost on me :) )

**Comment by paultag** [comment]
(Also, assuming this is actually talking about variadic functions and not just this "tag last" model specifically as a special case, in which case, still for it)

**Comment by adamchalmers** [comment]
> as little as possible existing as a built-in, and building as much as we can using the language itself. 

Agreed, this is why I think optional parameters have to be a KCL concept instead of using Rust enums that KCL can't access or use.

> I like the idea of variadic functions (so long as we document, autocomplete, and are able to statically lint) so this all def seems cool by my eye.

I wouldn't really say they're variadic, I'd say they're just functions where some parameters are optional. Functions will always have a fixed list of parameters with their own name and docs, but some of them can be declared as optional and will default to nil.

> The only yellow flag I want to throw up is that there are ast-mods that will need to change for this. but I'm happy to tackle the second half of the PR to fix that up.

Thanks @Irev-Dev that would be awesome

**Comment by Irev-Dev** [comment]
Sorry I think I mis-understood. Because this is just for `tangentialArcTo` there's no ast-mods involving that fn, so there's no hold up from me. We should be able to merge this one.

**Review by Irev-Dev — APPROVED** [review]

**Pull request merged**
