### PR TITLE
set Playwright actionTimeout to 15 seconds

### PR DESCRIPTION
**Pull request by ryanrosello-og**
Playwright global config change to prevent exceedingly long timeouts when certain actions fail 
e.g. button click

### CODE REVIEW

**Review by Irev-Dev — CHANGES_REQUESTED** [review]
Oh cool!

I think the failing macos playwright tests are related seeing some errors like
`TimeoutError: page.waitForEvent: Timeout 15000ms exceeded while waiting for event "console"`

`15000ms` makes me think it's this. Should we increase the timeout? or increase it just for these tests?

**Comment by Irev-Dev** [comment]
Or maybe we need to figure out why these tests need so long?

**Comment by ryanrosello-og** [comment]
I'm afraid this change won't address those particular issues yet.  This will only tweak the test execution so that tests fail faster - (so I dont have to wait too long when rerunning builds).  

Currently, `actionTimeout` is not specified, when a test fails on a particular action 
e.g. `clicking a button that is not ready to be clicked.`  

It will fallback to the test timeout (2 minutes)

I've also pushed some changes to:
* enable the html report, this will give insight into which tests are slow.
* enable screenshot on failure - for some reason the canvas does not render the lines in tracefiles.  Hoping the screenshot will capture the state of the canvas on failure

**Comment by Irev-Dev** [comment]
Okay, well I'm not sure exactly what's happening, but these 4 are consistently failing on this branch

image

So they must be related right, I've tried re-running the tests to make sure it's not a fluke.

**Comment by ryanrosello-og** [comment]
some progress, I'm getting a different failure now after my most recent commit.  The most recent failure is on my list to fix. 

```
  1) [webkit] › flow-tests.spec.ts:4165:7 › Sketch tests › Can delete most of a sketch and the line tool will still work 

    Error: Timed out 10000ms waiting for expect(locator).toBeVisible()

    Locator: locator('[data-message-type="execution-done"]').last()
    Expected: visible
    Received: <element(s) not found>
    Call log:
      - expect.toBeVisible with timeout 10000ms
      - waiting for locator('[data-message-type="execution-done"]').last()


       at test-utils.ts:49

      47 |
      48 | async function expectCmdLog(page: Page, locatorStr: string, timeout = 5000) {
    > 49 |   await expect(page.locator(locatorStr).last()).toBeVisible({ timeout })
         |                                                 ^
      50 | }
      51 |
      52 | async function waitForDefaultPlanesToBeVisible(page: Page) {

        at expectCmdLog (/Users/runner/work/modeling-app/modeling-app/e2e/playwright/test-utils.ts:49:49)
        at Object.expectCmdLog (/Users/runner/work/modeling-app/modeling-app/e2e/playwright/test-utils.ts:254:7)
        at /Users/runner/work/modeling-app/modeling-app/e2e/playwright/flow-tests.spec.ts:4200:13
```

I'll work on that first

**Comment by ryanrosello-og** [comment]
> Oh cool!
> 
> I think the failing macos playwright tests are related seeing some errors like `TimeoutError: page.waitForEvent: Timeout 15000ms exceeded while waiting for event "console"`
> 
> `15000ms` makes me think it's this. Should we increase the timeout? or increase it just for these tests?

I've extended the timeout for this particular call:

https://github.com/KittyCAD/modeling-app/pull/3115/commits/53fb96519de58d37cf6fbfaec1bbee0dea4e2171

**Comment by ryanrosello-og** [comment]
https://github.com/KittyCAD/modeling-app/pull/3115#issuecomment-2257178830

^ these failures are longer occuring

**Review by Irev-Dev — APPROVED** [review]

**Pull request merged**
