### PR TITLE
Add setting to disable blinking cursor

### PR DESCRIPTION
**Pull request by franknoirot**
Resolves https://github.com/KittyCAD/modeling-app/issues/1451 by adding a new setting under `text editor > blinking cursor` that does the following:
1. Updates the CodeMirror `cursorBlinkRate` to be `0`
2. Updates the `caret-color` on input and textarea elements to be `transparent`, hiding the cursor entirely. I am flabbergasted that in 2024 we can't control something like a `cursor-blink-rate` in CSS, but this is the workaround I'm forced into

## Demo

https://github.com/KittyCAD/modeling-app/assets/23481541/4d6576b6-ef19-4eb5-902e-690229cdf320

### CODE REVIEW

**Comment by Irev-Dev** [comment]
with the image in [8670cbd](https://github.com/KittyCAD/modeling-app/pull/2065/commits/8670cbd97980d39a7ae08d43444c98c9a2b8c7e3) https://github.com/KittyCAD/modeling-app/pull/2053 it's possible I re-introduced the bug with extrudes not being visible trying to stop there for being inconsistencies with buttons being disabled or not.

**Comment by Irev-Dev** [comment]
Hmm think this shouldn't be aimed at main, looks like it has commits from https://github.com/KittyCAD/modeling-app/pull/2063, I'll have a look at that one first.

**Comment by franknoirot** [comment]
Yeah sorry I should have put it in the description that I was going to wait for `franknoirot/sidebar` to get in and then rebase this real quick. I should have just branched this off of `main` though, that was dumb

**Comment by Irev-Dev** [comment]
If you aim this PR it at `franknoirot/sidebar` we can still choose not to merge it until your other PR is merged, but once it is, I believe github is smart enough to aim this one at main without the extra commits, even when `franknoirot/sidebar` is squashed on merged.

**Comment by Irev-Dev** [comment]
Up to you though.

**Pull request merged**
