### PR TITLE
Add an ArtifactMap pane to debug what's inside it more easily

### PR DESCRIPTION
**Pull request by franknoirot**
I'm still learning how the `ArtifactMap` type works and how I can adapt it to my use case for separating out the sketch statements from extrusions at the top level of the program. Having a pane like this will help me look inside it, and copy out its contents more easily.

It is turned off by default but can be toggled on by a setting (but not from the command bar, I'm getting annoyed with how many settings we have in there already).

## Demo
https://github.com/KittyCAD/modeling-app/assets/23481541/e2fc4186-42cf-4d8a-8e43-c8068e99b1bc

### CODE REVIEW

**Comment by jessfraz** [comment]
this will need to be added to the rust settings as well, happy to show you around, likely same place as debug is fine

**Comment by Irev-Dev** [comment]
Sorry I have a lot of questions.

Adding a whole panel just so we can inspect the contents of an internal data-structure seems a little overkill,
As adding `console.log(JSON.stringify(this.engineCommandManager.artifactMap))` to `src/lang/KclSingleton.ts:203` when you need it would also suffice.

I can definitely see the value in a debug panel but seems a bit odd if the only purpose is copy out to look at else where. LIke I can imagine having a search bar so that I could look at all artifacts with commandType of `extend_path` etc. I also think displaying it as is, is the hardest to grok, because it's nothing but a wall of Ids, the things that humans want to read is all the metadata within. But also to clarify, I don't actually think we should build the search tool or make the wall of id's more human friendly, I don't think it's worth our time.

I also don't really understand why this gets its own panel when the command logs, the astExplorer, and the send custom command debug tools are all in the debug panel?

Having things in the debug panel at least communicates to user's this isn't necessarily for them, I know the copy in the settings for this is `Whether to show the artifact map panel, a development tool` but seems confusing why it's distinct and gets its own place.

Sorry don't have any hard thoughts on how things should change, just seems a bit off to me.

**Comment by jessfraz** [comment]
I'm with @Irev-Dev if this can be done with a simple console log from the dev side, thats much better, we already have so much surface area I'd rather focus on making what works really good, otherwise this just adds more things that can potentially break

**Comment by dshaw** [comment]
Google's made copy/pasting into and out of the console harder. You can use this to grab the JSON from the console:

`copy(JSON.stringify(this.engineCommandManager.artifactMap))`

This works in both Chromium (Arc, Chrome) and Webkit (Tauri).

**Comment by dshaw** [comment]
I'm also -1 on adding UI that has only internal developer value. I say that while I've also been thinking of how nice it would be to have some sort of tracing view like [Chromium's Trace Event Profiling Tool](https://www.chromium.org/developers/how-tos/trace-event-profiling-tool/).

**Comment by franknoirot** [comment]
Makes sense all! I'm gonna close

**Pull request closed without merging**
