### PR TITLE
Cut release v0.25.5

### PR DESCRIPTION
**Pull request by nadr0**
## What's Changed
* Add a user-level projection setting, command, and toggle (#3983)
* Opening KCL sample now overwrites units (#3970)
* Add in min max data (#4029)
* More recursive docs types (#4028)
* One more pass of docs (#4026)
* Recusive docs (#4023)
*  preserve order of struct in autocomplete (#4018)
* Renames sketch group/extrude group (#4016)
* Updates path docs for website (#4019)
* KCL: Global rotation is fixed (#4017)
* Make engine stream react to `prefers-color-scheme` media query change (#4008)
* Kcl std lib docs use handlebars now so making changes should be better (1st pass) (#4007)
* Fix type-check error due to field addition (#4010)
* Add max-min to schemars (#4005)
* KCL: Better docs for patternTransform and int (#4002)
* Fix once cell version (#4004)
* KCL: 'rem' fn in stdlib (#3999)
* Remove .only error (#4003)
* KCL: Rotations in pattern transform (#3979)
* Disable failing step export test (#4000)
* Sketch on chamfer UI (#3918)
* 2D unclosed sketch Mirror (#3851)
* Fix dumb logic bug in indexing auto complete snippets (#3972)
* In-app toasts for electron-updater notifications (#3902)
* UI bug fix: padding-inline logic regression (#3967)
* Add ability to open KCL samples in-app (#3912)

**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.25.4...v0.25.5

### CODE REVIEW

**Comment by nadr0** [comment]
- [ ] Electron tests: external links open an external browser #3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
  - [ ] !
  - [ ] Bug bottom folder page
  - [ ] Bug bottom model render page
  - [ ] (Does not work on linux) mod + shift + .
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
  - [ ] Opens directory
  - [ ] Creates main file if empty
- [ ] (Did not do) If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
  - [ ] /home/kevin-nadro/Documents/zoo-modeling-app-projects/default/chassis-with-rails.kcl, took 47.60 seconds
- [ ] Electron tests: ensure we can open files that in tauri we would not be able to #3455  
  - [ ] Opening file
  - [ ] Editing file
  - [ ] ./out/Zoo\ Modeling\ App-linux-x64/zoo-modeling-app /home/kevin-nadro/smoke-test-file-permissions-linux/main.kcl
- [ ] Electron test: upgrading app should not cause user to have to auth again #3469 issues/3469
- [ ] Electron: logging in and authing works #3465 
- [ ] (Does not work on Linux) double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)

**Notes**
- Opening a path to a directory that doesn't exist, hangs, should we create the directory?
- Cannot figure out mod + shift + . on linux for core dump
- Double clicking files on linux does not work.
- Location to use the ZMA from the CLI ./out/Zoo\ Modeling\ App-linux-x64/zoo-modeling-app

**Comment by franknoirot** [comment]
MacOS

- [x] https://github.com/KittyCAD/modeling-app/issues/3373
- [x] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
- [x] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
	- This did not create a `main.kcl`, it just opened the default project directory
- [ ] If someone at the office, test you can hit `make` from the app and it works
	- Not in office, did not test
- [ ] Test updating versions works
- [x] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [x] https://github.com/KittyCAD/modeling-app/issues/3455
- [ ] https://github.com/KittyCAD/modeling-app/issues/3469
	- Cannot test
- [x] https://github.com/KittzzyCAD/modeling-app/issues/3465
- [x] double click to open files from finder opens new window each time (mac/windows)
- [x] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [ ] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
	- This is not implemented yet
- [ ] https://github.com/KittyCAD/modeling-app/issues/4038
	- Failed on MacOS, was signed out after clearing localStorage from app

**Comment by jessfraz** [comment]
i would love to get in kurts token fix but we can do another release this week with it

**Comment by franknoirot** [comment]
Ah yeah no sweat, I feel good otherwise so let me see if I can get his fix in real quick

**Pull request merged**
