### PR TITLE
Frank branding tweaks

### LINKED ISSUE #1232: rebrand paper cuts
Just going to put anything I notice here.
image

### PR DESCRIPTION
**Pull request by franknoirot**
Just some final feedback from the team, along with:
1. Update app icon to not have Kitt
2. Update Tauri app titles (@pierremtb I didn't mess with anything else, I figured it's probably safer for us to update the app signing domains later idk how that works though now that we're redirecting kittycad.io @jessfraz )
3. Fixes #1232

App icon for reference:
app-icon

### CODE REVIEW

**Review by pierremtb — CHANGES_REQUESTED** [review]
@franknoirot Cool this looks good for the most part! With the app name changes we will have to fix the last sections of the `.github/workflows/ci.yml` file

**Comment by pierremtb** [comment]
@franknoirot that's what your last commit produced in terms of artifacts

```
$ tree artifact -L 2                                                                                                                                                                                                             ⬡ 18.16.0
artifact
├── appimage
│   ├── build_appimage.sh
│   ├── kittycad-modeling.AppDir
│   └── kittycad-modeling_0.13.0_amd64.AppImage
├── deb
│   ├── kittycad-modeling_0.13.0_amd64
│   └── kittycad-modeling_0.13.0_amd64.deb
├── dmg
│   ├── Zoo Modeling_0.13.0_universal.dmg
│   ├── bundle_dmg.sh
│   ├── icon.icns
│   └── support
├── macos
│   └── Zoo Modeling.app
├── msi
│   └── Zoo Modeling_0.13.0_x64_en-US.msi
└── nsis
    └── Zoo Modeling_0.13.0_x64-setup.exe
```

**Comment by pierremtb** [comment]
@franknoirot Let me know if you want me to push directly on this branch, or do it in a subsequent PR

**Comment by franknoirot** [comment]
@pierremtb sorry for the delay, you can push directly on this PR! I agree I think the gravity is toward "Zoo Modeling App" over "Zoo Modeling" for now. Would you mind editing the CI workflow? That makes me nervous touching it for the first time like this

**Comment by pierremtb** [comment]
@franknoirot Pushed the changes. That's how the artifacts dir looks like now:

```
$ tree artifact\ \(3\) -L 2                                        ⬡ 18.16.0
artifact (3)
├── appimage
│   ├── build_appimage.sh
│   ├── zoo-modeling-app.AppDir
│   └── zoo-modeling-app_0.13.0_amd64.AppImage
├── deb
│   ├── zoo-modeling-app_0.13.0_amd64
│   └── zoo-modeling-app_0.13.0_amd64.deb
├── dmg
│   ├── Zoo Modeling App_0.13.0_universal.dmg
│   ├── bundle_dmg.sh
│   ├── icon.icns
│   └── support
├── macos
│   └── Zoo Modeling App.app
├── msi
│   └── Zoo Modeling App_0.13.0_x64_en-US.msi
└── nsis
    └── Zoo Modeling App_0.13.0_x64-setup.exe
```

**Comment by pierremtb** [comment]
Oops didn't mean to do that. Let's see how this build goes, then we can merge!

**Review by pierremtb — APPROVED** [review]
Tested on macOS, looks good.

**Pull request merged**
