### PR TITLE
Fix and test file tree operations

### PR DESCRIPTION
**Pull request by lf94**
Resolves https://github.com/KittyCAD/modeling-app/issues/3088

### CODE REVIEW

**Comment by lf94** [comment]
@jessfraz wanna put this over the goal line when you've got a moment ?

**Comment by jessfraz** [comment]
ah its just fmt i can push to your branch 1 sec

**Comment by jessfraz** [comment]
its not jsut fmt something else is messed up as well

**Comment by lf94** [comment]
```
  4 failed
    [Google Chrome] › projects.spec.ts:130:9 › Can export from electron app › Can export using commandBar 
    [Google Chrome] › projects.spec.ts:1780:7 › Deleting files from the file pane › when main.kcl exists, navigate to main.kcl 
    [Google Chrome] › regression-tests.spec.ts:431:7 › Regression tests › Network health indicator only appears in modeling view 
    [Google Chrome] › text-to-cad-tests.spec.ts:693:5 › Text-to-CAD functionality ──────────────────
    
```
_sigh_ No idea how but I'll look tomorrow

**Comment by lf94** [comment]
Closing, this branch name is breaking CI (branch name re-use)

**Pull request closed without merging**
