### PR TITLE
Remove most of modelingMachine.context.store

### PR DESCRIPTION
**Pull request by franknoirot**
By using the [`setPointerCapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) browser API, we can forgo the need to track cursor-stream state around React. In fact, I believe we can get rid of all but openPanes and have exactly the same user experience!

## Demo

https://github.com/user-attachments/assets/05600db1-fef4-4822-9182-deb19a6bb064

### CODE REVIEW

**Comment by Irev-Dev** [comment]
My one thought from the video is the stream resolution guard, might have been a debounce thing, I know Mike said something about not sending that through too often, but if it's already throttled should be fine.

Also now thing I would want to check is that dragging segment handles is still good, I mean it should be, and we have some tests for those (that don't seem to be the ones failing) but still worth a sanity check.

Only other though is the question I'm trying to ask myself for all PRs is "does this need a test" and I guess not since this is a refactor, and we have tests for rotating the camera already, there's nothing unique here that needs testing I think.

I guess that existing rotate camera test, could be changed to make sure that the mouse goes over the editor or similar?

**Comment by franknoirot** [comment]
> My one thought from the video is the stream resolution guard, might have been a debounce thing, I know Mike said something about not sending that through too often, but if it's already throttled should be fine.

I get you but I only think it would debounce by however fast XState could update, so maybe 1 event loop? I think the real debouncing is the [`deferExecution(() => { ... }, 500)`](https://github.com/KittyCAD/modeling-app/pull/3867/files#diff-b6994b9cccde4a4952069c83026de1070764e27eee95fba9189ee7db8d4f68e7R109) that makes it wait until .5 after resizing has stopped.

> Also one thing I would want to check is that dragging segment handles is still good, I mean it should be, and we have some tests for those (that don't seem to be the ones failing) but still worth a sanity check.

Good call, just checked and it's working fine

> Only other though is the question I'm trying to ask myself for all PRs is "does this need a test" and I guess not since this is a refactor, and we have tests for rotating the camera already, there's nothing unique here that needs testing I think.
> 
> I guess that existing rotate camera test, could be changed to make sure that the mouse goes over the editor or similar?

Oh man `Can moving camera`? Hah let me try it, I really don't want to introduce flakiness to it by mistake though

**Comment by franknoirot** [comment]
Found a way: instead of having that guard on a mousemove listener in App.tsx, I've added onEntry and onExit actions from that `showPlanes` state, which change and reset the selection filters, respectively.

**Comment by Irev-Dev** [comment]
> Ah damn I know why [this test](https://github.com/KittyCAD/modeling-app/actions/runs/10832140017/job/30055769589?pr=3867#step:26:621) is failing. [Here](https://github.com/KittyCAD/modeling-app/pull/3867/files#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2L87-L99) we return early without updating the highlighting if we're either in Sketch mode or in the showPlanes state, which I hadn't noticed. Is this because we don't want those planes to feel selectable when they're just there for scale/orientation reference? I'm gonna have to think about either a better way to attach that highlight handler or better determine the current state without directly referencing the modelingMachine 🤔

Pretty much nailed it, we added the planes on empty scene for AME, but I'm not even sure this is the end state UI, maybe we add something in three js (some axis or something) when scene is empty instead? that's almost certently harder and not worth doing for this PR.

> Found a way: instead of having that guard on a mousemove listener in App.tsx, I've added onEntry and onExit actions from that showPlanes state, which change and reset the selection filters, respectively.


I spoke too soon :p

**Review by Irev-Dev — APPROVED** [review]

**Pull request merged**
