### PR TITLE
remove _deffer

### PR DESCRIPTION
**Pull request by paultag**

### CODE REVIEW

**Comment by paultag** [comment]
this doesn't solve all the issues, just the most common trigger. we can still trigger this issue by racing the ast parser

**Comment by paultag** [comment]
@franknoirot  happy accident question for you

there's an `executeCode(true)` callsite that was formerly using the old signature (`force, zoomToFit`) to implicitly call `execute(true, false)` -- that I missed and is now calling `zoomToFit = true`. It's in the visual fit, and @jessfraz and I couldn't decide if this was good or bad. What do you think?

image

**Comment by jessfraz** [comment]
Actually I realized it re-layed out some of the selections tests outside of the screenshots so idk if anyone wants to do pixel math lol so maybe it’s not good? lol

**Comment by franknoirot** [comment]
> Actually I realized it re-layed out some of the selections tests outside of the screenshots so idk if anyone wants to do pixel math lol so maybe it’s not good? lol

Haha yeah I don't super want to go through and fix those tests right now. I actually think zooming-to-fit might make the "engine scale should be consistent" tests a little less consistent? Like the zoom-to-fit will make the segment fill the screen, regardless of scale going into sketch mode.

**Pull request merged**
