### PR TITLE
Cut release v0.14.0

### PR DESCRIPTION
**Pull request by pierremtb**
```
- Zoo rebrand (#1228, #1235)
- First consistency improvement for stdlib (#1096)
- Tauri update (#1157) 
- Updated test snapshots (#1224, #1223, #1179)
- Bug fixes for debug panel and unclickable stream (#1211, #1209)
- Less annoying web warnings (#1206)
- Removed execution-plan crate (#1207)
- Support for modeling commands in the Command Bar (#1204, #1196, #1184)
- Tauri tests on dev when the CI's BUILD_RELEASE is false (#1183)
- Execution plans should allow dynamic sized types (#1178)
```

### CODE REVIEW

**Review by pierremtb — COMMENTED** [review]
Tested the macOS build, looks all good:
- sign in
- create a file, create a sketch, extrude though Cmd+K (nice!!)
- export STL
- open an existing file
- sign out

**Review by pierremtb — COMMENTED** [review]
Same testing as :point_up: done on Win10 as well. All good

**Comment by pierremtb** [comment]
Waiting on zoo.dev changes from @franknoirot

**Comment by pierremtb** [comment]
Tested the latest Zoo Modeling App macOS build, looks all good:

- sign in
- create a file, create a sketch, extrude though Cmd+K (nice!!)
- export STL
- open an existing file
- sign out

**Comment by pierremtb** [comment]
Same on Win10. We're good to go!

**Comment by franknoirot** [comment]
Re-tested on MacOS post-domain change just to check OAuth and it was good! TYSM @pierremtb

**Pull request merged**
