### PR TITLE
Allow Vertical Scroll Wheel to affect Horizontal Scroll for Toolbar

### PR DESCRIPTION
**Pull request by rametta**
Previously the toolbar would not scroll when a vertical mouse wheel event occurred - which forced the user to drag the scroll bar horizontally to scroll, or use a horizontal scroll wheel (if their mouse has one).

This PR allows vertical scrolling to affect the horizontal scroll of the toolbar. Since there is no vertical scrolling space available here, the default vertical scrolling behaviour can be used as horizontal scrolling for a better UX.

Demo vid:

https://github.com/KittyCAD/modeling-app/assets/9722062/3981dcbb-8fa4-4ec2-af52-515d549ddf65

### CODE REVIEW

**Comment by jessfraz** [comment]
@rametta you are our first outside contributor! We need to mail you swag! Are you on discord DM me and I will put you in touch with someone for swag!

**Comment by jessfraz** [comment]
LGTM, tried it out! thank you! will merge when CI green :)

**Comment by jessfraz** [comment]
the windows build failure seems unrelated and more a github action bug so merging but cc @pierremtb who might know why?

**Comment by Irev-Dev** [comment]
Thank you @rametta 🙌

**Pull request merged**
