### PR TITLE
Add electron updater

### LINKED ISSUE #3528: Add electron updater

### PR DESCRIPTION
**Pull request by pierremtb**
Will fix #3528

### CODE REVIEW

**Comment by pierremtb** [comment]
Working update on macOS with the bump down at c71956e

image

**Comment by pierremtb** [comment]
Note that this is using the https://www.npmjs.com/package/update-electron-app package with a built in dialog. It seems possible with the lower-level autoUpdater API to kick our custom modals but I haven't succeeded hooking them up yet

**Comment by pierremtb** [comment]
Noted that this happens on the current macOS builds too. Need to see if it's something with forge

image

**Comment by jessfraz** [comment]
yeah we fixed the node_env error on main :)

**Comment by jessfraz** [comment]
if we name the binaries all the right things and publish the tauri update json as well, i bet it will work right? and upgrade peopel from tauri?

**Comment by pierremtb** [comment]
@jessfraz Awesome, will update!!

And yeah, I actually want to try that but I need to switch to the MSI bundles (instead of Squirrel) and I'm not sure if these support the auto updater. Hope to get a couple more things sorted out tomorrow and over the weekend

**Comment by pierremtb** [comment]
Tested on Windows too (ARM), this is how the default dialog looks:

image

**Comment by pierremtb** [comment]
Windows reopens automatically after update (Squirrel)

**Comment by pierremtb** [comment]
Confirmed that the app installed through the .dmg built with https://github.com/KittyCAD/modeling-app/pull/3600/commits/ed5d107103f5fa8f894878b7e293ac629bee7f8d allows for auto update

**Comment by pierremtb** [comment]
But it's not the case for MSI, at least not with the current options :'(

**Comment by jessfraz** [comment]
fwiw i think we need to use wix msi not squirrel for the file associations stuff i need for double click https://stackoverflow.com/questions/53535101/how-to-associate-a-file-extension-to-an-electron-app-multiplatform

**Comment by jessfraz** [comment]
yeah more docs https://github.com/electron/forge/issues/3339#issuecomment-2307404546

**Comment by jessfraz** [comment]
I think i got this here: https://github.com/KittyCAD/modeling-app/pull/3668

**Comment by jessfraz** [comment]
this is how we _kinda_ want it to look https://github.com/tauri-apps/tauri/commit/3b98141aa26f74c641a4090874247b97079bd58a#diff-a4ef6b8776c0e35518914c3788bc6449fc11cc1f99d2f9fd0380fc2ee49f7631

**Comment by pierremtb** [comment]
@jessfraz Awesome thank you!

**Comment by pierremtb** [comment]
Closed in favour #3717

**Pull request closed without merging**
