### PR TITLE
Make command bar arguments skippable, configure Extrude selection to be skippable

### PR DESCRIPTION
**Pull request by franknoirot**
1. Adds logic and types to support command bar arguments to be skippable
2. Implements our first skippable argument, the "selection" arg of the Extrude modeling command.

## Demo

Shows the `selection` argument being skipped by the user, then shows how the `distance` argument can be configured to be skippable as well.

https://github.com/KittyCAD/modeling-app/assets/23481541/cfaac091-8417-4a6f-bf94-5cfcbe36bc4d

### CODE REVIEW

**Comment by franknoirot** [comment]
@Irev-Dev is it possible that that the tests or the dev server in CI are being a bit flaky? I don't understand why `build-test-apps` is failing

**Comment by Irev-Dev** [comment]
I'm not sure, I'm seeing the tauri-driver test fail on ubuntu on my branch as well.

The error seems pretty opaque, maybe @pierremtb has some insights?

The playwright tests I fixed on my branch, so they are probably safe to ignore too.

**Review by Irev-Dev — APPROVED** [review]

**Comment by pierremtb** [comment]
@Irev-Dev from what I see here that step has started failing a after https://github.com/KittyCAD/modeling-app/pull/1352 on main
image

I'll work on it at https://github.com/KittyCAD/modeling-app/issues/1359

**Comment by pierremtb** [comment]
Merged https://github.com/KittyCAD/modeling-app/pull/1360 with a fix, would recommend hitting 'Update branch' here (Playwright is still not fixed tho so won't go green)

**Comment by pierremtb** [comment]
Yay build-test-apps is all green now! Blame goes to me 🏅

**Comment by franknoirot** [comment]
No no thanks for your help @pierremtb!

**Pull request merged**
