### PR TITLE
Cut release v0.24.0

### PR DESCRIPTION
**Pull request by pierremtb**
## What's Changed
* Straight sketch segments now display their length by Frank (#2935)
* Stream goes idle when tab is switched away from #savetheplanet thanks to Lee (#2940)
* Better syntax highlighting thanks to a Lezer grammar by Marijn Haverbeke 🤩 and Jess (#2967)
* Re-enabled, improved screen-space ambient occlusion by Kurt (#2956)
* Tags are now scoped to their functions thanks to Jess (#2941)
* Bug fix for math order of operations by Jess (#2398)
* A new unit indicator in lower-right corner, with menu to switch by Frank (#2937)
* Sketch editing bug fix by Lee (#2960)
* Bumped crates, updated docs by Jess & dependabot

**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.23.1...v0.24.0

### CODE REVIEW

**Comment by jessfraz** [comment]
Oh wait for my codemirror pr please

**Comment by jessfraz** [comment]
You didn’t have to close it!

**Comment by jessfraz** [comment]
Im gunna get it in today!

**Comment by pierremtb** [comment]
macOS smoke test went well

image

**Comment by pierremtb** [comment]
image

Windows looking good too

**Comment by pierremtb** [comment]
Can confirm with #2927 that the updater works on current main for both platforms

**Comment by pierremtb** [comment]
Noticed a few instances of the stream not starting, only seeing the white backdrop that a restart would fix. Seen in on macOS and Windows. Will try to file a bug later

**Comment by franknoirot** [comment]
Trivial failure of `Can edit a sketch that has been revolved in the same pipe` remaining, and a fix for that test is incoming with #2983, so I'm merging.

**Comment by pierremtb** [comment]
> Noticed a few instances of the stream not starting, only seeing the white backdrop that a restart would fix. Seen in on macOS and Windows. Will try to file a bug later

Filed issue at https://github.com/KittyCAD/modeling-app/issues/2995

**Pull request merged**
