### PR TITLE
Add app version to UI in Settings

### PR DESCRIPTION
**Pull request by franknoirot**
Resolves https://github.com/KittyCAD/modeling-app/issues/877 after way too long.

## Demo

https://github.com/KittyCAD/modeling-app/assets/23481541/94005634-992d-48c3-b3a4-c6226a315edb

### CODE REVIEW

**Comment by franknoirot** [comment]
Also resolves https://github.com/KittyCAD/modeling-app/issues/144 in a minimal sort of way

**Review by Irev-Dev — APPROVED** [review]

**Comment by franknoirot** [comment]
Ugh Playwright doesn't know about Vite defines I guess, gotta troubleshoot.

**Comment by pierremtb** [comment]
@franknoirot Awesome!! Esp. useful on Windows where there is no About dialog like on macOS.

Looks like it's the tauri-driver that's unhappy: https://github.com/KittyCAD/modeling-app/actions/runs/7805282671/job/21297382715?pr=1351#step:20:33

Would it make more sense to use on the desktop app at least? https://tauri.app/v1/api/js/app#getversion
Maybe falling back to npm when not available?

**Comment by franknoirot** [comment]
Oh hell yeah thanks for sharing that @pierremtb  that's very helpful. Yeah sounds good, I'll rework to use that in the Tauri context.

**Comment by pierremtb** [comment]
@franknoirot cools, looks pretty clean! Also just realized `main` is also broken for build-test-apps ubuntu, so it has nothing to do with these changes https://github.com/KittyCAD/modeling-app/actions/runs/7807596699/job/21296277422

**Pull request merged**
