### PR TITLE
Cut release v0.22.7

### PR DESCRIPTION
**Pull request by Irev-Dev**
## What's Changed

Most importantly the syntax for tags is now `$myTag` to declare a tag and `myTag` to then use it later. If you format your code via `Alt+Shift+F` or the three dot menu on the code panel it will fix this for you. We will keep backwards compatibility with string tags for a few releases but you should update your code now.

The nice thing about this is now the code editor autocompletes tag names for you and now you can get better errors when you abuse tags.

So for example this code:
```
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([65.87, 230.28], %)
  |> line([248.25, -79.48], %)
  |> line([-74.04, -283.09], %, 'myTag')
  |> line([-192.72, 235.18], %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
  |> extrude(100, %)

const sketch002 = startSketchOn(sketch001, 'myTag')
  |> startProfileAt([185.8, 131.39], %)
  |> line([62.76, -12.99], %)
  |> line([-27.05, -47.61], %)
  |> line([-43.65, 9.37], %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
```

Becomes:
```
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([65.87, 230.28], %)
  |> line([248.25, -79.48], %)
  |> line([-74.04, -283.09], %, $myTag)
  |> line([-192.72, 235.18], %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
  |> extrude(100, %)

const sketch002 = startSketchOn(sketch001, myTag)
  |> startProfileAt([185.8, 131.39], %)
  |> line([62.76, -12.99], %)
  |> line([-27.05, -47.61], %)
  |> line([-43.65, 9.37], %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
```

* More semantic tokens modifiers (#2823)
* Move walk handlers out of lint (#2822)
* Update onboarding KCL (#2820)
* Only show one error at once (#2801)
* More expressive semantic tokens (#2814)
* Add more tests for various scenarios (#2812)
* Allow lifetime refs in KCL stdlib parameters (#2802)
* Hide grid (#2777)
* Fix some recast bugs (#2781)
* Tag as top level construct  (#2769)
* Tags are globals (#2795)
* Add sketch tool events to command bar (#2708)
* Allow for sketching on the face of a chamfer in kcl (#2760)
* Execute chamfers and fillets early if in a pattern (#2759)
* Semantic tokens used for highlighting (#2806)
* Delete key works for click and point (#2752)
* Rework zoom (https://github.com/KittyCAD/modeling-app/pull/2798)
* Add setting for grid visibility (https://github.com/KittyCAD/modeling-app/pull/2838)
* Fallback colors for different browsers (https://github.com/KittyCAD/modeling-app/pull/2770)

**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.22.6...v0.22.7

### CODE REVIEW

**Comment by pierremtb** [comment]
Testing on macOS:
- sign in
- open project
- close project
- create project
- create sketch
- create rectangle
- create var
- resize with var
- extrude with var
- export to STL: failed
- export to OBJ: failed

Issue created #2840

**Comment by jessfraz** [comment]
between ubuntu and macos they playwright arent failing on the same tests so i think we are okay.

**Comment by jessfraz** [comment]
the tests work locally for me and i pushed a fix to one to make more reliable

**Comment by pierremtb** [comment]
Did my usual test round on macOS, looks good. Will try Windows in a minute

**Comment by pierremtb** [comment]
Windows looking good too

**Review by pierremtb — APPROVED** [review]
Local tests on Windows and macOS look good!

**Pull request merged**
