### PR TITLE
Add --retries to playwright flow-tests

### PR DESCRIPTION
**Pull request by pierremtb**

### CODE REVIEW

**Comment by Irev-Dev** [comment]
playwright has been setup with 3 retries, do you think we should bring that down to 2?
https://github.com/KittyCAD/modeling-app/blob/main/playwright.config.ts#L19

**Comment by pierremtb** [comment]
@Irev-Dev oh shoot, I thought it had zero as default 🤦 However it feels like I'm beating the odds here, no?

image

**Comment by pierremtb** [comment]
@Irev-Dev shoot, this one just failed https://github.com/KittyCAD/modeling-app/pull/1476/commits/b193c7318894eff7106c50ac78fed82a9f54ccec 🤦 🤦

**Comment by Irev-Dev** [comment]
> However it feels like I'm beating the odds here, no?

🤷 I find playwright to be pretty reliable these days. One of the biggest culprits was this auto complete test that I've been able to make more robust, since then I've been happy.

**Comment by pierremtb** [comment]
@Irev-Dev Alright thanks for the input. Closing!

**Pull request closed without merging**
