### PR TITLE
Prevent full re-render on final KCL file deletion

### PR DESCRIPTION
**Pull request by franknoirot**
@JordanNoone pointed out that there was a "crash" or something wrong when deleting the final KCL file in a project's top directory. This was a full refresh that felt more catastrophic in dark mode due to a separate issue fixed by #3794. But react-router-dom's navigation should prevent a full re-render of the page anyway, so I investigated and found the very smol cause.

## Demo

https://github.com/user-attachments/assets/ed91503f-c103-455d-b405-98d9621527be

### CODE REVIEW

**Review by jtran — APPROVED** [review]
Nice.

**Comment by lf94** [comment]
Nice I thought the original did what the new does :D

**Review by Irev-Dev — APPROVED** [review]

**Comment by franknoirot** [comment]
This might have a real playwright failure https://github.com/KittyCAD/modeling-app/actions/runs/10729880216/job/29759277503?pr=3808#step:20:19343

**Comment by lf94** [comment]
I suspect the error is caused by a race in Windows

**Comment by franknoirot** [comment]
I'm going to look for `/main.kcl` somewhere in the codebase, I think something about this change generates a Unix-style path


https://github.com/user-attachments/assets/2b328a4d-7f70-47a9-a4e2-ada9c3bf2529

**Comment by lf94** [comment]
Interesting, I am very wrong about my original idea :laughing: 

Ok, this is good! I think this is way more tangible. I can help with this tomorrow 100%

**Comment by franknoirot** [comment]
Thank you! I do not get it, it's not the `main.kcl` think I was off. It's so weird to me that it's Windows-specific

**Comment by lf94** [comment]
I'll put this over the line; just leave it to me so you can get it off your mind

**Comment by lf94** [comment]
FYI I have not forgotten about this. It's related to the file related stuff so I'm saving it for then.

**Comment by franknoirot** [comment]
I'm gonna close this because it's stale, it's easy to resurrect, and it overlaps with the class of bugs you're squashing with your project view work.

**Pull request closed without merging**
