### PR TITLE
Nadro/3799/perf

### PR DESCRIPTION
**Pull request by nadr0**
closes https://github.com/KittyCAD/modeling-app/issues/3799

- Added `RouteProvider` to watch `route` changes at an application level for `mark` events.
- Added logic to add `Go to Settings, Telemetry, Home` routes within the `CommandBarProvider`
- Added new custom icon for telemetry
- Added several `marks` and `markOnce` spans to track Jess's performance requirements
- Added `TelemetryExplorer` to view the telemetry data that is stored locally
- Added an override to the CodeMirror syntaxhighlighting function to wrap it in performance `mark` calls
- Added `performance.ts` which is a library for `mark` `markOnce` and `getMarks` taken from VSCode and altered
- Added `telemetry.ts` that has a bunch of formatters and print functions for the mark data
- Added a telemetry modal that renders the same way as the settings modal. Users can view the telemetry data
- Added an icon in the lower right hand corner for telemetry

https://github.com/user-attachments/assets/6099c13c-d090-4c66-9552-db736ce1e26a

### CODE REVIEW

**Comment by lf94** [comment]
@nadr0 could you clean this and I'll review and approve

**Comment by nadr0** [comment]
> @nadr0 could you clean this and I'll review and approve

lol yeah I'll clean up the `import dog from './beepbeepargs'`

**Comment by lf94** [comment]
fmt appears to be failing, I'll run it quickly

**Review by lf94 — APPROVED** [review]
Looks good to me; nothing particularly catches my eye as being "bad". @franknoirot could you give this a look over quickly too?

**Pull request merged**
