### PR TITLE
Cut release v0.26.3

### PR DESCRIPTION
**Pull request by franknoirot**
## Changed
* File tree acts more like VS Code's file tree (#4392)
* Creating new projects asks for project name before creating (#4109)

## Added
* Snap-to-origin and axis behavior for sketch profile starts and segments (#4344)
* KCL: `polygon` standard library function (Thanks @guptaarnav) (#4300)
* KCL: Add ability to `push` to arrays (Thanks @guptaarnav (#4232)
* Implement a simple startSketchOn / offsetPlane lint rule (#4384)
* KCL: More ways to reference paths (#4387)
* Error if assertEqual's epsilon value is invalid (#4329)
* Show top-level project directory name in file tree pane header (#4165)
* Add ability to open, create, rename, and delete projects from inside one via command bar (#4109)

## Fixed
* Fix KCL source ranges to know which source file they point to (#4418)
* Fixed directory/file selection logic to deselect folders properly and always hightlight files.  (#4408)

## Contributors
* Thanks again to @guptaarnav for more thoughtful contributions!

### CODE REVIEW

**Review by lf94 — APPROVED** [review]

**Comment by franknoirot** [comment]
MacOS smoke testing:
- [ ] Mash keyboard in code editor
- [ ] https://github.com/KittyCAD/modeling-app/issues/3373
- [ ] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
- [ ] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [ ] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [ ] Test updating versions works
- [ ] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [ ] https://github.com/KittyCAD/modeling-app/issues/3455
- [ ] https://github.com/KittyCAD/modeling-app/issues/3469
- [ ] https://github.com/KittyCAD/modeling-app/issues/3465
- [ ] double click to open files from finder opens new window each time (mac/windows)
- [ ] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [ ] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
- [ ] https://github.com/KittyCAD/modeling-app/issues/4038

**Comment by franknoirot** [comment]
Windows smoke testing:
- [x] Mash keyboard in code editor
- [x] https://github.com/KittyCAD/modeling-app/issues/3373
- [x] coredump will open github issue with stuff populated (from home and project page) there are different ways to trigger it as well (! button at top, bug at bottom, `mod + shift + .`)
- [x] running app.{app,exe} path/to/file opens the kcl file (all oses)
- [x] running app.{app,exe} path/to/dir opens the directory and any kcl file in it or creates a main.kcl if empty (all oses)
- [ ] If someone at the office, test you can hit `make` from the app and it works
- [x] Test updating versions works
- [x] until we have a performance test, sanity check that time to open file directly from command line is not shit
- [ ] https://github.com/KittyCAD/modeling-app/issues/3455
- [x] https://github.com/KittyCAD/modeling-app/issues/3469
- [x] https://github.com/KittyCAD/modeling-app/issues/3465
- [x] double click to open files from finder opens new window each time (mac/windows)
- [x] export from the app works and opens a file picker ux (needs to be manual since we override for playwright)
- [x] Ensure that a loading toast appears when testing the auto-updater, saying the download has begun
- [x] https://github.com/KittyCAD/modeling-app/issues/4038

**Comment by franknoirot** [comment]
Both MacOS and Windows tests were solid, and updater tests went on without a hitch

**Review by jtran — COMMENTED** [review]
👍

**Pull request merged**
