### PR TITLE
Add lexical scope and redefining variables in functions

### LINKED ISSUE #1285: Scoping error between program body and function definition scope
The following code creates a `Cannot redefine varShouldBeScoppedToFn` error

```typescript
fn fnDef = (varShouldBeScoppedToFn) => {
//          ^Cannot redefine varShouldBeScoppedToFn
  return varShouldBeScoppedToFn + 2
}

const result = fnDef(2)

const varShouldBeScoppedToFn = 6
const part001 = startSketchOn('-XZ')
  |> startProfileAt([-5.8, 23.97], %)
  |> line([21.62, -4.8], %)

const result2 = fnDef(4)
```
even though this variable should be within the function scope

note the first call `const result = fnDef(2)` doesn't trigger it

It's the second one `const result2 = fnDef(4)`, must have something to do with the function call after the variable declaration.

Here's a more minimal viable reproduction
```typescript
fn fnDef = (varShouldBeScoppedToFn) => {
  return varShouldBeScoppedToFn + 2
}

const varShouldBeScoppedToFn = 6

const result2 = fnDef(4)
```

Moving the variable declaration to the top still has the error
```typescript
const varShouldBeScoppedToFn = 6

fn fnDef = (varShouldBeScoppedToFn) => {
  return varShouldBeScoppedToFn + 2
}

const result2 = fnDef(4)
```

### PR DESCRIPTION
**Pull request by jtran**
Fixes #1285.

# Overview

Prior to this, KCL implemented dynamic scope. With dynamic scope, in order to determine whether a variable is defined at a given point and what its type is, you needed to execute the program to follow its flow. This becomes harder and harder for anyone reading KCL code, especially when we start adding loops, recursion, etc.

```kcl
// With dynamic scope, this works.
fn returnX = () => {
  // What does x refer to?
  return x
}

const x = 2
const answer = returnX()
```

This PR changes KCL to use [lexical scope](https://en.wikipedia.org/wiki/Scope_(computer_science)). This generally makes it easier to reason about a snippet of code because you can find an identifier's definition above it in the source to determine its type. The runtime call stack cannot affect it. This also opens the doors to static type checking, if we ever decide to go down that route.

```kcl
const x = 2

// With lexical scope, x must be defined above.
fn returnX = () => {
  // It's clear what x refers to.
  return x
}

const answer = returnX()
```

Functions now also have their own scope, so redefining an identifier inside a function that's already used outside is possible. It shadows whatever is defined in the parent scope.

```kcl
const x = 2

fn returnX = () => {
  const x = 42
  return x
}

// The answer is 42. Here, x is still 2.
const answer = returnX()
```

# Details

Variables and tags now need to be defined before use. When I say "before", I mean higher up in the source code. It's no longer about execution order. This is how almost all real programming languages work. This is how `let` and `const` in JavaScript work. Interestingly, `var` and `function` in JavaScript are [hoisted](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting) to the beginning of the scope. We may want to add something like that in the future, especially if we ever want to allow mutually recursive functions. But there's a reason `let` and `const` are the new default for developers using modern JavaScript.

Another change this PR makes is hiding the implementation of ProgramMemory on the TypeScript side in a class. Besides hopefully making it easier to migrate to Rust one day, this should make it easier to change the internals of ProgramMemory going forward. One reason to change it again is to improve KCL runtime performance.

# Breaking Change

This is a breaking change because programs that used to look like this no longer work.

```kcl
fn returnX = () => {
  return x
}

const x = 2
const answer = returnX()
```

The way to fix it is to move the variable definition to (textually) above its use.

```kcl
const x = 2

fn returnX = () => {
  return x
}

const answer = returnX()
```

### CODE REVIEW

**Review by Irev-Dev — APPROVED** [review]

**Comment by Irev-Dev** [comment]
>  static type checking, if we ever decide to go down that route.

Would be dope!

**Comment by Irev-Dev** [comment]
LFG

**Comment by lf94** [comment]
This looks really well done. Awesome job @jtran . @adamchalmers you'll really want to see this so it stays in your context of what's going on while you've been away, I think you'll be quite pleased :D

**Comment by lf94** [comment]
It looks like there's a legit test failure. I'd really like to see any failures fixed before merging this, just to keep the practice of not merging breaking changes until all tests pass.

**Comment by jtran** [comment]
`serial_test_plumbus_fillets` is the problematic test. I think I fixed it, but it fails with "No such edge or face exists". The KCL also fails in the production desktop app. The old version of the KCL on `main` also fails in the production desktop app. So either something is wrong with the engine, or this KCL test case isn't right.

**Comment by lf94** [comment]
I meant the playwright test (I think the wasm-lib tests are generally broken)

**Pull request merged**
