### PR TITLE
Make tag last optional param everywhere

### LINKED ISSUE #1730: lineTo tag should be consistent with tangentialArcTo and others
We adopted a new standard of using an optional tag parameter at the end of commands.
lineTo came before this decision, so it hasn't yet been updated to that new standard.

See https://github.com/KittyCAD/modeling-app/issues/1006 for details on the change.

### PR DESCRIPTION
**Pull request by iterion**
closes #1730

### CODE REVIEW

**Comment by jessfraz** [comment]
Awesome thanks for doing this lgtm when all tests pas cc @jgomez720 to update his samples everywhere and I can bump the cli after

**Comment by jgomez720** [comment]
Oh super cool. Just to make sure I'm understanding this right, this is changing the structure from
```
|> line({to: [5, 5], tag: 'mySuperNiceLine'}, %)
```

to
```
|> line([5, 5], %, 'mySuperNiceLine')
```

**Comment by iterion** [comment]
Yep, you got it! Anything that took an optional `tag: "something"` will change to the second format you gave where tag is always the optional last parameter.

**Comment by jessfraz** [comment]
why isnt cargo test running?

**Comment by jessfraz** [comment]
rebase on this once merged https://github.com/KittyCAD/modeling-app/pull/1740

**Comment by Irev-Dev** [comment]
I'm going to revert this, sorry guys, ast mods need to be updated at the same time otherwise the app produces broken code

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/assets/29681384/a12fe0b9-7cc8-4289-9c2c-cf529d378e0e

The classic `object Object`

**Comment by Irev-Dev** [comment]
FYI found a regression with this.
https://github.com/KittyCAD/modeling-app/pull/1747

Nice work though 👏

**Comment by Irev-Dev** [comment]
The bug I found was it adding the classic js `object Object` as a tag 😂 
https://github.com/KittyCAD/modeling-app/assets/29681384/d3e03193-e85f-4f96-bff9-ff73d82dbfd6

**Comment by iterion** [comment]
HA, of course I missed something! I even fixed a bug just like that one elsewhere. Thanks for the quick fix and explanation. I wonder if I can get some unit test coverage on that, the existing unit tests were invaluable in making this change.

**Comment by Irev-Dev** [comment]
Well I found it on my "sketchOnFace" branch after merging in main, because I did have extrude working back when it was my fake engine it's probably found some `tag` logic that hasn't been used in a long time. Probably means it was under tested before, but this might also be a timing thing that I happen to be working on sketchOnFace when this went through, so maybe less of a regression and more of a regression in my branch ya know.

I do have one e2e test for the sketch on face, I plan on adding more. I just added a `add unit test for the extrusion codemod` in my [TODO list](https://github.com/KittyCAD/modeling-app/pull/1664) in the description.

**Comment by Irev-Dev** [comment]
SketchOnExtrudedFace unit test is in my branch now too

[9129f9a](https://github.com/KittyCAD/modeling-app/pull/1664/commits/9129f9abc055c1f1a241d906aaeb5315b795c1c8)

**Comment by iterion** [comment]
Fantastic, thanks @Irev-Dev!

**Pull request merged**
