### PR TITLE
try turn back on macos

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by jessfraz** [comment]
@ryanrosello-og thought you might have ideas on this one, on macOS the tests hang on can’t wait on console but on windows/ubuntu they are fine, in this PR I tried not using the playwright version of google chrome and instead use the one in brew and it had same issue, it’s super weird

**Comment by ryanrosello-og** [comment]
hello @jessfraz 


I had a crack at this and  found the following:

* From the [Github doco](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md), apparently they already have Google Chrome installed on the runner so we shouldn't need to mess around installing it ourselves:








* The current retry logic in the workflow wipes out useful artifacts like the tracefile so I created a branch (`ryanrosello-og/troubleshoot-turn-on-macos`) off your branch and hacked up the playwright.yml for troubleshooting:

The tests seems to be falling over here...




I've never seen this error message before, I'm hoping this makes sense to you:


```
THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Could not create a WebGL context, VENDOR = 0xffff, DEVICE = 0xffff, GL_VENDOR = Google Inc. (Google), GL_RENDERER = ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (LLVM 10.0.0) (0x0000C0DE)), SwiftShader driver-5.0.0), GL_VERSION = 21.0.19, Sandboxed = no, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .
THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Failed to create a WebGL2 context.
THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Could not create a WebGL context, VENDOR = 0xffff, DEVICE = 0xffff, GL_VENDOR = Google Inc. (Google), GL_RENDERER = ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (LLVM 10.0.0) (0x0000C0DE)), SwiftShader driver-5.0.0), GL_VERSION = 21.0.19, Sandboxed = no, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .
THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Failed to create a WebGL2 context.
THREE.WebGLRenderer: Error creating WebGL context.
Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (http://localhost:3000/node_modules/.vite/deps/chunk-DEEFU7IG.js?v=3b43911a:16976:19)
    at new SceneInfra (http://localhost:3000/src/clientSideScene/sceneInfra.ts:185:21)
    at http://localhost:3000/src/lib/singletons.ts:14:27
Cannot access 'editorManager' before initialization
ReferenceError: Cannot access 'editorManager' before initialization
    at KclManager.setDiagnosticsForCurrentErrors (http://localhost:3000/src/lang/KclSingleton.ts:91:5)
    at set kclErrors (http://localhost:3000/src/lang/KclSingleton.ts:83:10)
    at KclManager.safeParse (http://localhost:3000/src/lang/KclSingleton.ts:163:20)
    at http://localhost:3000/src/lang/KclSingleton.ts:126:23
```


This is the tracefile: 

[trace.zip](https://github.com/user-attachments/files/16647093/trace.zip)


You can view it using https://trace.playwright.dev/

**Comment by jessfraz** [comment]
Yeah what I don’t understand is why the other os don’t have this same issue, it would at least make sense if they were consistent

**Comment by ryanrosello-og** [comment]
i have some good news and some bad news @jessfraz :

**Good news:**  
my googling found this existing open Playwright issue:
https://github.com/microsoft/playwright/issues/30585

**Bad news:**  
this was previously working but apparently some upstream project reverted the fix which then broke Playwright.

**Comment by ryanrosello-og** [comment]
[https://github.com/KittyCAD/modeling-app/commit/5c291d2c216a4ceb075bdd8e22e7416b7bb8ff49#diff-96a7f8b65f5a714b52cddef[…]cccf604d08789fde9ecb6429bac2](https://github.com/KittyCAD/modeling-app/commit/5c291d2c216a4ceb075bdd8e22e7416b7bb8ff49#diff-96a7f8b65f5a714b52cddefba64ba0dc1aa6cccf604d08789fde9ecb6429bac2)
^ this change seemed to have worked :thinking_face:



https://github.com/KittyCAD/modeling-app/actions/runs/10449661591/job/28932445400
[6:26](https://kittycadworkspace.slack.com/archives/C07DNTC89CM/p1724055982505769?thread_ts=1724013784.174719&cid=C07DNTC89CM)
I thought there was a requirement for the app to use the actual Google Chrome browser (which had some required codec) instead of Playwrights' own chromium browser

if we wanted to roll with this, then its going to need some logic when triggering the tests:

- ubuntu-latest will use the "Google Chrome" project
- windows-latest will use the "Google Chrome" project
- macos-14 will use the "chromium" project

**Comment by ryanrosello-og** [comment]
yeah nah, tried a bunch of other things as well, none of them worked :(


https://github.com/KittyCAD/modeling-app/commit/24f23514128e0b9e3d788ba26ef2dbb4b0db5af0
https://github.com/KittyCAD/modeling-app/commit/1d570b94491dda3fd549ed77e76229f8aa9a8fb8
https://github.com/KittyCAD/modeling-app/commit/c43bf6bb99b6ee4ae32f6ae980499364aa3d3588

Looks like we'll have to wait for next Playwright release:

**Comment by jessfraz** [comment]
oh whoa okay nuts, I just like knowing the reason thank you! makes sense!

**Pull request closed without merging**
