### PR TITLE
Make web app warning banner in the middle of the screen and simpler

### PR DESCRIPTION
**Pull request by franknoirot**
Before:

Screenshot 2024-09-30 at 12 22 44 PM

After:

Screenshot 2024-09-30 at 12 21 17 PM

### CODE REVIEW

**Comment by lf94** [comment]
I would not say 'web app may have breaking changes', just has bad optics.

**Comment by franknoirot** [comment]
> I would not say 'web app may have breaking changes', just has bad optics.

Okay but I do think we should say something that explains why the desktop app is more reliable. People think web apps are less reliable than desktop apps already, and the reason our desktop app is more reliable is more about it being on a slower release cycle than anything.

**Comment by Irev-Dev** [comment]
Maybe just, "the web app is not officially supported", that kinda implies that we not fixing web app specific issues. and than maybe "proceed at my own risk" instead of "okay I understand"?

**Comment by Irev-Dev** [comment]
I also think the "download desktop app" should be more of a CTA button, stand out more.

**Comment by lf94** [comment]
Love @Irev-Dev 's suggestions. Yes this would work well I believe. It biases people toward the desktop app while not shitting on the web app. :laughing:

**Comment by franknoirot** [comment]
Sounds good, can do

**Comment by franknoirot** [comment]
Screenshot 2024-10-02 at 1 44 03 PM

**Review by lf94 — APPROVED** [review]

**Pull request merged**
