### PR TITLE
Remove E2E tests requirement on Cut Release v PR

### LINKED ISSUE #4296: Remove E2E tests requirement on Cut Release PR

### PR DESCRIPTION
**Pull request by pierremtb**
Fixes #4296

>  I don't like the way it's done at all. Can't have weirdo checks on PR titles spread across workflows like that. I think as we gained stability on pw tests we could just reject this for now?

### CODE REVIEW

**Comment by lf94** [comment]
@pierremtb , @nadr0 added kcl-samples as a new test suite - could you contact him about making _that_ a required test for release?

**Comment by nadr0** [comment]
> @pierremtb , @nadr0 added kcl-samples as a new test suite - could you contact him about making _that_ a required test for release?

The job is called `yarn-unit-test-kcl-samples`. I made it required as of right now. I thought I did two days ago but I appears I didn't click the save button.

**Comment by pierremtb** [comment]
@lf94 @nadr0 Yes looks good in the settings!

Back to this PR here, I don't like the way it's done at all. Can't have weirdo checks on PR titles spread across workflows like that. I think as we gained stability on pw tests we could just reject this for now?

**Comment by pierremtb** [comment]
Closing for now as per comment above. Will reopen if needed.

**Pull request closed without merging**
