### PR TITLE
Cut release v0.11.0

### PR DESCRIPTION
**Pull request by pierremtb**
## Release Notes

- Improvements
  - kcl parser now uses [Winnow](https://docs.rs/winnow/latest/winnow/) for 70x faster parsing
  - modeling state is now managed with [XState](https://stately.ai/docs/xstate) for more reliable architecture (and cool generated diagrams)
  - Many bugfixes around entering and exiting modes as a result of XState migration
  - Fix for culling distance
  - Allow OS + / to toggle comments in editor (thanks @rametta :heart_eyes_cat:)
  - Upgrade to Tauri v1.5
  - Error banner if WASM fails (thanks @MollyBoydTaylor :fire:)
  - Better code highlighting when selecting vertices and edges with point-and click
  - Move tool no longer breaks after editing via the code editor
- Features
  - ⦜ New sketch constraints
  - 🧀 Holes in sketches (kcl only, not point-and-click)
  - 🗂️ Multi-file support (desktop only)

### CODE REVIEW

**Comment by jessfraz** [comment]
Oh I was just talking to @franknoirot and up to you @Irev-Dev but I was thinking we wait to cut a release until we have a couple days w xstate, since theres a lot of follow up issues but maybe its fine to go out now?

**Comment by pierremtb** [comment]
@jessfraz all good, I'll leave it as Draft till we're good to go

**Comment by jessfraz** [comment]
since https://github.com/KittyCAD/modeling-app/issues/834 is a regression we should wait on that for a release

**Comment by pierremtb** [comment]
Will try to go thru the list on macOS today for the build out of https://github.com/KittyCAD/modeling-app/pull/826/commits/6bfd419bbfbbb9d173975fbc82a9e57df08800b6
- [x] can authenticate
- [ ] code stays between refreshes of app
- [ ] in tauri app, code re-executed when selecting a new file
- [ ] code executes on initial page load in web app
- [ ] typing in the editor re-executes the model and changes it based on your code
- [ ] when engine stops and restarts, code re-executes and you get the gizmo and planes
- [ ] on startsketch click, you see the three planes
- [ ] you can create new sketches w click and point
- [ ] you can create a sketch on any plane (xy, yz, xz, -xy, -yz, -xz)
- [ ] you can change your keyboard shortcuts to other settings and they work
- [ ] you can reload the onboarding from any screen and the onboarding works
- [ ] you can edit sketches, as long as they are not closed
- [ ] you should not be able to edit sketches that are closed, the button should not appear
- [ ] you can move lines in edit sketch and it updates the code (more than once)
- [ ] you can move lines in a fresh sketch from Start Sketch and it updates the code (more than once)
- [ ] you do not see move button when you have constraints in your sketch
- [ ] in tauri can create new projects
- [ ] can apply constraints in edit sketch mode
- [ ] you can export your model in each file type and the exported file is valid

**Comment by pierremtb** [comment]
New list on macOS out of https://github.com/KittyCAD/modeling-app/pull/826#:~:text=Verified-,a7aaedc,-vercel

- [ ]  can authenticate
- [ ]  code stays between refreshes of app
- [ ]  in tauri app, code re-executed when selecting a new file
- [ ]  code executes on initial page load in web app
- [ ]  typing in the editor re-executes the model and changes it based on your code
- [ ]  when engine stops and restarts, code re-executes and you get the gizmo and planes
- [ ]  on startsketch click, you see the three planes
- [ ]  you can create new sketches w click and point
- [ ]  you can create a sketch on any plane (xy, yz, xz, -xy, -yz, -xz)
- [ ]  you can change your keyboard shortcuts to other settings and they work
- [ ]  you can reload the onboarding from any screen and the onboarding works
- [ ]  you can edit sketches, as long as they are not closed
- [ ]  you should not be able to edit sketches that are closed, the button should not appear
- [ ]  you can move lines in edit sketch and it updates the code (more than once)
- [ ]  you can move lines in a fresh sketch from Start Sketch and it updates the code (more than once)
- [ ]  you do not see move button when you have constraints in your sketch
- [ ]  in tauri can create new projects
- [ ]  can apply constraints in edit sketch mode
- [ ]  you can export your model in each file type and the exported file is valid

**Comment by pierremtb** [comment]
Ghost sketch, when clearing the code before extruding, and starting fresh

image

**Comment by pierremtb** [comment]
Test list on Windows out of https://github.com/KittyCAD/modeling-app/pull/826

- [ ] can authenticate
- [ ]  code stays between refreshes of app
- [ ]  in tauri app, code re-executed when selecting a new file
- [ ]  code executes on initial page load in web app
- [ ]  typing in the editor re-executes the model and changes it based on your code
- [ ]  when engine stops and restarts, code re-executes and you get the gizmo and planes
- [ ]  on startsketch click, you see the three planes
- [ ]  you can create new sketches w click and point
- [ ]  you can create a sketch on any plane (xy, yz, xz, -xy, -yz, -xz)
- [ ]  you can change your keyboard shortcuts to other settings and they work
- [ ]  you can reload the onboarding from any screen and the onboarding works
- [ ]  you can edit sketches, as long as they are not closed
- [ ]  you should not be able to edit sketches that are closed, the button should not appear
- [ ]  you can move lines in edit sketch and it updates the code (more than once)
- [ ]  you can move lines in a fresh sketch from Start Sketch and it updates the code (more than once)
- [ ]  you do not see move button when you have constraints in your sketch
- [ ]  in tauri can create new projects
- [ ]  can apply constraints in edit sketch mode
- [ ]  you can export your model in each file type and the exported file is valid

**Comment by pierremtb** [comment]
Saw the ghost sketch going after going Home and opening a new file on Windows:
image

**Comment by pierremtb** [comment]
Creating a new sketch here but nothing shows up in the code

image

**Comment by franknoirot** [comment]
MacOS re-testing:
- [ ] can authenticate
- [ ] code stays between refreshes of app
- [ ] in tauri app, code re-executed when selecting a new file
- [ ]  code executes on initial page load in web app
- [ ]  typing in the editor re-executes the model and changes it based on your code
- [ ]  when engine stops and restarts, code re-executes and you get the gizmo and planes
- [ ]  on startsketch click, you see the three planes
- [ ]  you can create new sketches w click and point
- [ ]  you can create a sketch on any plane (xy, yz, xz, -xy, -yz, -xz)
- [ ]  you can change your keyboard shortcuts to other settings and they work
- [ ]  you can reload the onboarding from any screen and the onboarding works
- [ ]  you can edit sketches, as long as they are not closed
- [ ]  you should not be able to edit sketches that are closed, the button should not appear
- [ ]  you can move lines in edit sketch and it updates the code (more than once)
- [ ]  you can move lines in a fresh sketch from Start Sketch and it updates the code (more than once)
- [ ]  you do not see move button when you have constraints in your sketch
- [ ]  in tauri can create new projects
- [ ]  can apply constraints in edit sketch mode
- [ ]  you can export your model in each file type and the exported file is valid

**Comment by franknoirot** [comment]
Confirmed that the Windows issues appear resolved @pierremtb, I only discovered a sketch bug

**Comment by franknoirot** [comment]
That sketch bug has been resolved, and after re-checking on MacOS that things are looking good, it's time to merge! 🚀

**Pull request merged**
