### PR TITLE
Ghost text

### PR DESCRIPTION
**Pull request by jessfraz**
- [x] lsp server for copilot
- [x] client side autocompletions with code mirror
- [x] hit kittycad api for completions from the lsp server
- [x] implement kittycad api endpoint for completions (https://github.com/KittyCAD/api-deux/pull/1538)
- [x] pass in our auth token to the lsp server
- [x] fix the weird reqwests + lsp-tower bug

### CODE REVIEW

**Comment by Irev-Dev** [comment]
Is there any problem with using the term "copilot ™️"?

**Comment by jessfraz** [comment]
literally everyone does so I can't imagine there is

**Comment by jessfraz** [comment]
@Irev-Dev this is all hooked up but I have it hard coded to return zero results because right now it is pointed at our API but not the model we are going to want to use :) so basically this allows us to merge this, make sure the two plugins dont eff with each other, and we make sure theres no weird behavior, and i dont ahve weird rebases, but you just wont see any ghost text for the time being

**Review by Irev-Dev — APPROVED** [review]

**Comment by jessfraz** [comment]
the ubuntu test failure is from the file settings PR, frank is looking into it and the other failure is just spurious timeouts everything else is green so merging

**Pull request merged**
