### PR TITLE
Cut release v0.25.2

### PR DESCRIPTION
**Pull request by franknoirot**
## What's Changed
* Sketch segment labels now align to segments (#3796)
* The "reset settings" button now only resets current level (#3855)
* Updates to the onboarding example project bracket (#3874)
* So many bug fixes and architecture improvements from the whole team ❤️ 

**Full Changelog**: https://github.com/KittyCAD/modeling-app/compare/v0.25.1...v0.25.2

### CODE REVIEW

**Comment by pierremtb** [comment]
macOS updater test succeeded but Windows failed due to a signature issue. Need to check if it's just my test build or a real issue

**Comment by pierremtb** [comment]
False alarm: the logs in the test build I had pushed were saying the signature had failed, just retried it and it went through https://github.com/KittyCAD/modeling-app/actions/runs/10862129034/job/30190414221 

Now the updater test works on Windows too

**Comment by pierremtb** [comment]
Done brief app smoke test on macOS and Windows too

**Comment by franknoirot** [comment]
Just completed the [smoke test list](https://github.com/KittyCAD/modeling-app/issues/3588) on MacOS as well. Everything seems to be in order.

**Review by jtran — APPROVED** [review]
I just went through the manual tests on Debian (excluding updating the app), and it looks good.

**Pull request merged**
