### PR TITLE
Fix: on settings close go back to the same file

### PR DESCRIPTION
**Pull request by lf94**
Resolves https://github.com/KittyCAD/modeling-app/issues/3537

### CODE REVIEW

**Comment by jessfraz** [comment]
needs a test or it will regress

**Comment by lf94** [comment]
Yep sounds good

**Comment by lf94** [comment]
@jessfraz I'm in the middle of writing the test :laughing:

**Comment by jessfraz** [comment]
oh lol sorry i was updating everyones branches

**Comment by franknoirot** [comment]
Could you remove the unused imports?

**Comment by lf94** [comment]
Yep no problem. I wouldn't mind if we made this an error

**Comment by lf94** [comment]
I'll fix the other tests tomorrow. @franknoirot caught it's probably useAbsoluteFilePath changed causing the others to break. I think I might have a workaround but we'll see tomorrow.

**Comment by lf94** [comment]
Ok it's not that I broke the tests it's that my change actually caught some bad code in other places - ok, nice. For example, the onboard replay assumes /main.kcl . It should not do this and instead let the fileLoader determine the default file to load.

**Comment by lf94** [comment]
@iterion 's code actually fixes this in another way so I reverted my change, so this PR equates to a nice test.

**Pull request merged**
